// ============================================================
//  Linda's Korea Guide — curated places
//  Add a place: copy any object below, fill the fields, done.
//  Fields you can leave null: cuisine, place_id, instagram, hours,
//  station, lat, lng (map button falls back to a name search).
//  city: "seoul" | "busan" | "gyeongju"  (gyeongju shows under the Busan tab)
//  category: matcha|sushi|japanese|chinese|korean|italian|dessert|cafe|photo|landmark
//  spice: 0 none/NA · 1 mild · 2 medium · 3 hot   (only shown for food)
//  pork_lamb_free: true safe · false contains pork/lamb · null = NA (cafe/dessert)
// ============================================================

const PLACES = [
  // ---------- SEOUL · Matcha / Dessert ----------
  {
    id: "super-matcha-seongsu",
    name: "Super Matcha Seongsu",
    name_kr: "슈퍼말차 성수",
    city: "seoul",
    area: "Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Hand-whisked matcha latte, matcha roll cake",
    blurb: "Minimalist matcha specialist — strong, real matcha. A fan favorite and a great first stop.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5474581,
    lng: 127.0436943,
    place_id: "ChIJGz1f9SSlfDURcPrJUN2BSVs",
    instagram: "supermatcha.official",
    hours: "11:00–21:00 daily",
    station: "Seongsu Stn (Line 2), 6 min walk",
    price: "₩₩",
    must_try: true
  },
  {
    id: "cortz-yongsan",
    name: "Cortz",
    name_kr: "코르츠",
    city: "seoul",
    area: "Yongsan",
    category: "matcha",
    cuisine: null,
    signature: "Coconut-milk matcha latte, chilling espresso",
    blurb: "A current matcha 'holy spot' — loved by celeb Jeon Somi. Smooth coconut-milk matcha is the move.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null,               // TODO verify: look up exact lat/lng/place_id
    lng: null,
    place_id: null,
    instagram: null,         // TODO verify handle
    hours: null,
    station: null,
    price: "₩₩",
    must_try: true
  },
  {
    id: "unforget-seongsu",
    name: "Unforget",
    name_kr: "언포겟",
    city: "seoul",
    area: "Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Matcha macarons",
    blurb: "Harper's Bazaar pick. 3rd-floor dessert cafe overlooking the subway line — peak Seongsu aesthetic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null,               // TODO verify coords + place_id
    lng: null,
    place_id: null,
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "cafe-tilde-namyeong",
    name: "Cafe Tilde",
    name_kr: "틸데",
    city: "seoul",
    area: "Namyeong (Yongsan)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha cream latte, matcha bingsu (wine bar at night)",
    blurb: "Foreigners repeatedly call it the best matcha in Korea. Cafe by day, wine bar by night.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.5435969,
    lng: 126.9734246,
    place_id: "ChIJHx3sFgCjfDURpv-rTpfpVIw",
    instagram: "tilde.cafe.wine",
    hours: "12:00–23:00, closed Mon",
    station: "Namyeong Stn (Line 1)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "toroto-seongsu",
    name: "Toroto",
    name_kr: "토로토로",
    city: "seoul",
    area: "Seongsu",
    category: "dessert",
    cuisine: null,
    signature: "Strawberry matcha, tiramisu, basque cheesecake",
    blurb: "Japanese-vibe basement dessert cafe — dim, moody, and very photogenic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.538938,
    lng: 127.0564606,
    place_id: "ChIJrzUcIgClfDURsdhImQWrDk8",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "notre-don-seoulsup",
    name: "Notre Don",
    name_kr: "노트르동",
    city: "seoul",
    area: "Seoul Forest / Seongsu",
    category: "dessert",
    cuisine: null,
    signature: "Madeleines, pistachio pastries",
    blurb: "High-reputation pastry shop near Seoul Forest. Grab a box for the road.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.5473154,
    lng: 127.0400271,
    place_id: "ChIJZyWHihCjfDURiUxkfFoiQGQ",
    instagram: null,
    hours: null,
    station: "Seoul Forest Stn (Suin-Bundang)",
    price: "₩₩",
    must_try: false
  },

  // ---------- SEOUL near-suburb (Bundang / Pangyo — only if she goes south) ----------
  {
    id: "orvcha-pangyo",
    name: "Orvcha",
    name_kr: "오브차",
    city: "seoul",
    area: "Pangyo (Seongnam)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha bingsu, strawberry mochi",
    blurb: "Tatami tea-house with a calm, lab-like aesthetic. Worth it if you're already south of the river.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.3851171,
    lng: 127.1109977,
    place_id: "ChIJW8VrgMVZezURRmfNKXn7JnM",
    instagram: null,
    hours: null,
    station: "Pangyo area",
    price: "₩₩",
    must_try: false
  },
  {
    id: "daily-oasis-yatap",
    name: "Daily Oasis",
    name_kr: "데일리오아시스 분당 야탑",
    city: "seoul",
    area: "Yatap (Seongnam)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha lemonade, mango bingsu",
    blurb: "English-friendly staff — an easy, relaxed stop if you head to Bundang.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.410009,
    lng: 127.1300286,
    place_id: "ChIJhw3XW5mpfDURR-If-l7TMmE",
    instagram: null,
    hours: null,
    station: "Yatap Stn (Bundang Line)",
    price: "₩₩",
    must_try: false
  },

  // ---------- BUSAN · Matcha / Dessert ----------
  {
    id: "cafe-hitaro-sajik",
    name: "Cafe Hitaro",
    name_kr: "카페 히타로",
    city: "busan",
    area: "Sajik-dong (Dongnae)",
    category: "matcha",
    cuisine: null,
    signature: "Uji matcha latte (whisked to order), matcha shot latte, madeleine",
    blurb: "Busan's matcha holy grail — premium Uji matcha in a Japanese-house setting. 5 min from Sajik Stadium.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1926,           // TODO verify exact coords
    lng: 129.0611,
    place_id: "ChIJo32Vo2mVaDUR1fgxX99AxBY",
    instagram: null,
    hours: null,
    station: "Sajik Stn (Line 3)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "simmian-cheongsapo",
    name: "Simmian",
    name_kr: "심미안",
    city: "busan",
    area: "Cheongsapo (Haeundae)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha bingsu, matcha crepe cake, strawberry matcha latte",
    blurb: "Quiet hidden gem near the sea — sit on the floor, traditional style. Beautiful and calm.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1617136,
    lng: 129.188696,
    place_id: "ChIJPWoJM2yNaDURYDpEMm4wA4w",
    instagram: null,
    hours: null,
    station: "Cheongsapo (Sky Capsule area)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "yeonui-yanggwa-gwangalli",
    name: "Yeonui Yanggwa",
    name_kr: "연의양과 광안점",
    city: "busan",
    area: "Gwangalli",
    category: "dessert",
    cuisine: null,
    signature: "Bingsu (watermelon / mango)",
    blurb: "Fresh-fruit bingsu a short walk from Gwangalli beach. Perfect summer cool-down.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 35.1574301,
    lng: 129.1217163,
    place_id: "ChIJ_XOb-2DtaDURfxJJsIpcHdI",
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "deokmi-atelier-gwangalli",
    name: "Deokmi Atelier",
    name_kr: "덕미 아틀리에",
    city: "busan",
    area: "Gwangalli",
    category: "cafe",
    cuisine: null,
    signature: "Sandwiches, tea",
    blurb: "Charming 4.9-rated brunch spot near Gwangalli, with resident cats. Heads up: jambon items contain ham — ask for a pork-free option.",
    spice: 0,
    pork_lamb_free: false,   // jambon = ham; ask staff for pork-free choice
    photo_spot: true,
    lat: 35.1564665,
    lng: 129.1206828,
    place_id: "ChIJ20yPvNntaDURwR9_3bONaeE",
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ---------- GYEONGJU (Busan daytrip — shows under Busan tab) ----------
  {
    id: "noka-gyeongju",
    name: "NOKA",
    name_kr: "노카 녹아",
    city: "gyeongju",
    area: "Hwangnam-dong, Gyeongju",
    category: "dessert",
    cuisine: null,
    signature: "Matcha gelato (pick your sweetness / bitterness), hojicha",
    blurb: "A matcha ice-cream destination in old-town Gyeongju — you choose how sweet or bitter. Worth the daytrip.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.8360948,
    lng: 129.2117779,
    place_id: "ChIJ_z1MHVVPZjUR5F-zYNhCJDA",
    instagram: null,
    hours: null,
    station: "Gyeongju (daytrip from Busan)",
    price: "₩₩",
    must_try: false
  }

  // ---------- TODO: expand each category (keep balanced) ----------
  // SEOUL:  sushi ×3–4 · italian ×2–3 · korean (no-pork!) ×3–4 · chinese ×2 · landmarks/photo ×3–5
  // BUSAN:  sushi/japanese · korean seafood (Jagalchi, pork-free) · landmarks
  //         (Gamcheon Culture Village, Haedong Yonggungsa, Gwangalli, Haeundae, Cheongsapo Sky Capsule)
  // JAPAN:  add as 3rd tab later (Tokyo? Osaka? Kyoto? Uji = matcha holy land) — ask Linda her cities.
];
