// ============================================================
//  Linda's Korea Guide — curated places
//  Add a place: copy any object below, fill the fields, done.
//  Fields you can leave null: cuisine, place_id, instagram, hours,
//  station, lat, lng (map button falls back to a name search).
//  city: "seoul" | "busan" | "gyeongju"  (gyeongju shows under the Busan tab)
//  category: matcha|sushi|japanese|chinese|korean|italian|dessert|cafe|photo|landmark
//  spice: 0 none/NA · 1 mild · 2 medium · 3 hot   (only shown for food)
//  pork_lamb_free: true safe · false contains pork/lamb · null = NA (cafe/dessert)
// ============================================================

const PLACES = [
  // ---------- SEOUL · Matcha / Dessert ----------
  {
    id: "super-matcha-seongsu",
    name: "Super Matcha Seongsu",
    name_kr: "슈퍼말차 성수",
    city: "seoul",
    area: "Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Hand-whisked matcha latte, matcha roll cake",
    blurb: "Minimalist matcha specialist — strong, real matcha. A fan favorite and a great first stop.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5474581,
    lng: 127.0436943,
    place_id: "ChIJGz1f9SSlfDURcPrJUN2BSVs",
    instagram: "supermatcha.official",
    hours: "11:00–21:00 daily",
    station: "Seongsu Stn (Line 2), 6 min walk",
    price: "₩₩",
    must_try: true
  },
  {
    id: "cortz-yongsan",
    name: "Cortz",
    name_kr: "코르츠",
    city: "seoul",
    area: "Yongsan",
    category: "matcha",
    cuisine: null,
    signature: "Coconut-milk matcha latte, chilling espresso",
    blurb: "A current matcha 'holy spot' — loved by celeb Jeon Somi. Smooth coconut-milk matcha is the move.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null,               // TODO verify: look up exact lat/lng/place_id
    lng: null,
    place_id: null,
    instagram: null,         // TODO verify handle
    hours: null,
    station: null,
    price: "₩₩",
    must_try: true
  },
  {
    id: "unforget-seongsu",
    name: "Unforget",
    name_kr: "언포겟",
    city: "seoul",
    area: "Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Matcha macarons",
    blurb: "Harper's Bazaar pick. 3rd-floor dessert cafe overlooking the subway line — peak Seongsu aesthetic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null,               // TODO verify coords + place_id
    lng: null,
    place_id: null,
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "cafe-tilde-namyeong",
    name: "Cafe Tilde",
    name_kr: "틸데",
    city: "seoul",
    area: "Namyeong (Yongsan)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha cream latte, matcha bingsu (wine bar at night)",
    blurb: "Foreigners repeatedly call it the best matcha in Korea. Cafe by day, wine bar by night.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.5435969,
    lng: 126.9734246,
    place_id: "ChIJHx3sFgCjfDURpv-rTpfpVIw",
    instagram: "tilde.cafe.wine",
    hours: "12:00–23:00, closed Mon",
    station: "Namyeong Stn (Line 1)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "toroto-seongsu",
    name: "Toroto",
    name_kr: "토로토로",
    city: "seoul",
    area: "Seongsu",
    category: "dessert",
    cuisine: null,
    signature: "Strawberry matcha, tiramisu, basque cheesecake",
    blurb: "Japanese-vibe basement dessert cafe — dim, moody, and very photogenic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.538938,
    lng: 127.0564606,
    place_id: "ChIJrzUcIgClfDURsdhImQWrDk8",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "notre-don-seoulsup",
    name: "Notre Don",
    name_kr: "노트르동",
    city: "seoul",
    area: "Seoul Forest / Seongsu",
    category: "dessert",
    cuisine: null,
    signature: "Madeleines, pistachio pastries",
    blurb: "High-reputation pastry shop near Seoul Forest. Grab a box for the road.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.5473154,
    lng: 127.0400271,
    place_id: "ChIJZyWHihCjfDURiUxkfFoiQGQ",
    instagram: null,
    hours: null,
    station: "Seoul Forest Stn (Suin-Bundang)",
    price: "₩₩",
    must_try: false
  },

  // ---------- SEOUL near-suburb (Bundang / Pangyo — only if she goes south) ----------
  {
    id: "orvcha-pangyo",
    name: "Orvcha",
    name_kr: "오브차",
    city: "seoul",
    area: "Pangyo (Seongnam)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha bingsu, strawberry mochi",
    blurb: "Tatami tea-house with a calm, lab-like aesthetic. Worth it if you're already south of the river.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.3851171,
    lng: 127.1109977,
    place_id: "ChIJW8VrgMVZezURRmfNKXn7JnM",
    instagram: null,
    hours: null,
    station: "Pangyo area",
    price: "₩₩",
    must_try: false
  },
  {
    id: "daily-oasis-yatap",
    name: "Daily Oasis",
    name_kr: "데일리오아시스 분당 야탑",
    city: "seoul",
    area: "Yatap (Seongnam)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha lemonade, mango bingsu",
    blurb: "English-friendly staff — an easy, relaxed stop if you head to Bundang.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.410009,
    lng: 127.1300286,
    place_id: "ChIJhw3XW5mpfDURR-If-l7TMmE",
    instagram: null,
    hours: null,
    station: "Yatap Stn (Bundang Line)",
    price: "₩₩",
    must_try: false
  },

  // ---------- BUSAN · Matcha / Dessert ----------
  {
    id: "cafe-hitaro-sajik",
    name: "Cafe Hitaro",
    name_kr: "카페 히타로",
    city: "busan",
    area: "Sajik-dong (Dongnae)",
    category: "matcha",
    cuisine: null,
    signature: "Uji matcha latte (whisked to order), matcha shot latte, madeleine",
    blurb: "Busan's matcha holy grail — premium Uji matcha in a Japanese-house setting. 5 min from Sajik Stadium.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1926,           // TODO verify exact coords
    lng: 129.0611,
    place_id: "ChIJo32Vo2mVaDUR1fgxX99AxBY",
    instagram: null,
    hours: null,
    station: "Sajik Stn (Line 3)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "simmian-cheongsapo",
    name: "Simmian",
    name_kr: "심미안",
    city: "busan",
    area: "Cheongsapo (Haeundae)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha bingsu, matcha crepe cake, strawberry matcha latte",
    blurb: "Quiet hidden gem near the sea — sit on the floor, traditional style. Beautiful and calm.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1617136,
    lng: 129.188696,
    place_id: "ChIJPWoJM2yNaDURYDpEMm4wA4w",
    instagram: null,
    hours: null,
    station: "Cheongsapo (Sky Capsule area)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "yeonui-yanggwa-gwangalli",
    name: "Yeonui Yanggwa",
    name_kr: "연의양과 광안점",
    city: "busan",
    area: "Gwangalli",
    category: "dessert",
    cuisine: null,
    signature: "Bingsu (watermelon / mango)",
    blurb: "Fresh-fruit bingsu a short walk from Gwangalli beach. Perfect summer cool-down.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 35.1574301,
    lng: 129.1217163,
    place_id: "ChIJ_XOb-2DtaDURfxJJsIpcHdI",
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "deokmi-atelier-gwangalli",
    name: "Deokmi Atelier",
    name_kr: "덕미 아틀리에",
    city: "busan",
    area: "Gwangalli",
    category: "cafe",
    cuisine: null,
    signature: "Sandwiches, tea",
    blurb: "Charming 4.9-rated brunch spot near Gwangalli, with resident cats. Heads up: jambon items contain ham — ask for a pork-free option.",
    spice: 0,
    pork_lamb_free: false,   // jambon = ham; ask staff for pork-free choice
    photo_spot: true,
    lat: 35.1564665,
    lng: 129.1206828,
    place_id: "ChIJ20yPvNntaDURwR9_3bONaeE",
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ---------- GYEONGJU (Busan daytrip — shows under Busan tab) ----------
  {
    id: "noka-gyeongju",
    name: "NOKA",
    name_kr: "노카 녹아",
    city: "gyeongju",
    area: "Hwangnam-dong, Gyeongju",
    category: "dessert",
    cuisine: null,
    signature: "Matcha gelato (pick your sweetness / bitterness), hojicha",
    blurb: "A matcha ice-cream destination in old-town Gyeongju — you choose how sweet or bitter. Worth the daytrip.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.8360948,
    lng: 129.2117779,
    place_id: "ChIJ_z1MHVVPZjUR5F-zYNhCJDA",
    instagram: null,
    hours: null,
    station: "Gyeongju (daytrip from Busan)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Sushi (Linda loves sushi — all pork-free, spice 0) ==========
  {
    id: "mine-sushi-yeoksam",
    name: "Mine Sushi",
    name_kr: "미네 스시",
    city: "seoul",
    area: "Yeoksam (Gangnam)",
    category: "sushi",
    cuisine: "japanese",
    signature: "Counter omakase, Edomae nigiri",
    blurb: "Widely called Seoul's best traditional Edomae sushi — sit at the counter for the omakase. A real treat for a sushi lover.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,   // TODO verify coords
    instagram: null,
    hours: null,
    station: "Yeoksam Stn (Line 2)",
    price: "₩₩₩",
    must_try: true
  },
  {
    id: "gatten-sushi-gangnam",
    name: "Gatten Sushi",
    name_kr: "갓덴스시 강남",
    city: "seoul",
    area: "Gangnam",
    category: "sushi",
    cuisine: "japanese",
    signature: "Conveyor-belt nigiri, fresh & affordable",
    blurb: "Fun, casual conveyor-belt sushi — grab what looks good, easy on the wallet, no reservation needed.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Gangnam Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Italian ==========
  {
    id: "zio-cucina-ikseon",
    name: "Zio Cucina Ikseon",
    name_kr: "지오쿠치나 익선",
    city: "seoul",
    area: "Ikseon-dong",
    category: "italian",
    cuisine: "italian",
    signature: "Four-cheese pizza, porcini pasta, brick-oven pizza",
    blurb: "Cozy Italian tucked in Ikseon-dong's pretty hanok alleys. Plenty of cheese/veggie/seafood options — just skip the pancetta pastas.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Jongno 3-ga Stn (Lines 1/3/5)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "kitchen-485-hongdae",
    name: "Kitchen 485",
    name_kr: "키친485",
    city: "seoul",
    area: "Hongdae",
    category: "italian",
    cuisine: "italian",
    signature: "Spinach tagliatelle, mushroom sauce, handmade pizza",
    blurb: "A Hongdae favorite for authentic pizza and fresh pasta — the veggie-forward signatures are naturally pork-free.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Korean (no-pork picks — chicken / beef / spice-tagged) ==========
  {
    id: "tosokchon-samgyetang",
    name: "Tosokchon Samgyetang",
    name_kr: "토속촌 삼계탕",
    city: "seoul",
    area: "Jongno (near Gyeongbokgung)",
    category: "korean",
    cuisine: "korean",
    signature: "Samgyetang — ginseng chicken soup (not spicy)",
    blurb: "The famous ginseng-chicken soup right by Gyeongbokgung — whole young chicken stuffed with rice, garlic, jujube. Chicken only, zero spice. Perfect after the palace.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Gyeongbokgung Stn (Line 3)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "byeokje-galbi",
    name: "Byeokje Galbi",
    name_kr: "벽제갈비",
    city: "seoul",
    area: "Songpa",
    category: "korean",
    cuisine: "korean",
    signature: "Premium beef galbi (Korean BBQ), galbi-tang",
    blurb: "High-end beef-only Korean BBQ — no pork on the grill here. A splurge, but a legendary one.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Munjeong Stn (Line 8)",
    price: "₩₩₩",
    must_try: false
  },
  {
    id: "yoogane-dakgalbi-myeongdong",
    name: "Yoogane Dak-galbi",
    name_kr: "유가네 닭갈비 명동",
    city: "seoul",
    area: "Myeongdong",
    category: "korean",
    cuisine: "korean",
    signature: "Dak-galbi — stir-fried spicy chicken",
    blurb: "Sizzling stir-fried chicken with rice — tourist-friendly with English menus. Medium spicy; you can ask them to tone it down.",
    spice: 2,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Myeongdong Stn (Line 4)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Chinese (pork-risky cuisine — flagged to be safe) ==========
  {
    id: "madam-ming-yeouido",
    name: "Madam Ming",
    name_kr: "마담밍",
    city: "seoul",
    area: "Yeouido",
    category: "chinese",
    cuisine: "chinese",
    signature: "Jjamppong naengmyeon (cold seafood noodles, spice 1–5)",
    blurb: "A 20-year specialist in cold seafood jjamppong noodles — you pick the spice level. Seafood-based, but Korean-Chinese kitchens use pork, so ask for the no-pork/seafood option.",
    spice: 2,
    pork_lamb_free: false,   // Korean-Chinese: assume pork unless confirmed — ask staff
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Yeouido Stn (Lines 5/9)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Landmarks / Photo spots ==========
  {
    id: "gyeongbokgung",
    name: "Gyeongbokgung Palace",
    name_kr: "경복궁",
    city: "seoul",
    area: "Jongno",
    category: "landmark",
    cuisine: null,
    signature: "Main royal palace, changing-of-the-guard, hanbok photos",
    blurb: "Seoul's grand Joseon-era palace. Rent a hanbok nearby to get in free and take gorgeous photos. Closed Tuesdays.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: "09:00–18:00, closed Tue",
    station: "Gyeongbokgung Stn (Line 3), exit 5",
    price: "₩",
    must_try: true
  },
  {
    id: "bukchon-hanok-village",
    name: "Bukchon Hanok Village",
    name_kr: "북촌한옥마을",
    city: "seoul",
    area: "Jongno",
    category: "photo",
    cuisine: null,
    signature: "Traditional hanok alleyways, rooftop views",
    blurb: "Quiet lanes of restored hanok houses between the palaces — the classic Seoul postcard shot. Keep your voice down; people live here.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Anguk Stn (Line 3), exit 2",
    price: "Free",
    must_try: false
  },
  {
    id: "ikseon-dong",
    name: "Ikseon-dong Hanok Street",
    name_kr: "익선동",
    city: "seoul",
    area: "Jongno",
    category: "photo",
    cuisine: null,
    signature: "Trendy hanok cafes, dessert & photo alleys",
    blurb: "A maze of old hanok turned into cute cafes, dessert shops and boutiques — very photogenic, great for an afternoon wander.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Jongno 3-ga Stn (Lines 1/3/5)",
    price: "Free",
    must_try: false
  },
  {
    id: "seoul-forest",
    name: "Seoul Forest",
    name_kr: "서울숲",
    city: "seoul",
    area: "Seongsu",
    category: "landmark",
    cuisine: null,
    signature: "Big city park, deer enclosure, tree-lined paths",
    blurb: "A leafy park right by the Seongsu cafes — perfect to pair with your matcha crawl. Lovely light in the late afternoon.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seoul Forest Stn (Suin-Bundang)",
    price: "Free",
    must_try: false
  },
  {
    id: "yeouido-hangang-park",
    name: "Yeouido Hangang Park",
    name_kr: "여의도 한강공원",
    city: "seoul",
    area: "Yeouido",
    category: "landmark",
    cuisine: null,
    signature: "Han River picnic spot, sunset, night views",
    blurb: "Grab a mat and some snacks and watch the sun set over the Han River — a favorite local evening. Instant-ramyeon machines on site.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Yeouinaru Stn (Line 5), exit 2/3",
    price: "Free",
    must_try: false
  },
  {
    id: "namsan-tower",
    name: "N Seoul Tower (Namsan)",
    name_kr: "남산서울타워",
    city: "seoul",
    area: "Yongsan",
    category: "landmark",
    cuisine: null,
    signature: "City-wide views, cable car, night lights",
    blurb: "Ride the cable car up Namsan for the best panoramic view of Seoul — especially magical after dark.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Myeongdong Stn (Line 4) + cable car",
    price: "₩₩",
    must_try: false
  },

  // ========== BUSAN · Sushi / Japanese ==========
  {
    id: "sushi-iruka-haeundae",
    name: "Sushi Iruka",
    name_kr: "스시 이루카",
    city: "busan",
    area: "Marine City (Haeundae)",
    category: "sushi",
    cuisine: "japanese",
    signature: "Edomae omakase, Japanese sake pairing",
    blurb: "Calm, high-quality Edomae sushi in Marine City — fresh daily catch and a quiet counter. Book ahead.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Marine City (Haeundae)",
    price: "₩₩₩",
    must_try: false
  },
  {
    id: "sushi-yama-haeundae",
    name: "Sushi Yama",
    name_kr: "스시야마 해운대",
    city: "busan",
    area: "Jung-dong (Haeundae)",
    category: "sushi",
    cuisine: "japanese",
    signature: "Conveyor-belt sushi, fresh & good value",
    blurb: "Popular casual conveyor-belt sushi near Haeundae — reliable, cheap and quick when you just want a plate of nigiri.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Haeundae Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ========== BUSAN · Landmarks / Photo spots ==========
  {
    id: "gamcheon-culture-village",
    name: "Gamcheon Culture Village",
    name_kr: "감천문화마을",
    city: "busan",
    area: "Saha-gu",
    category: "photo",
    cuisine: null,
    signature: "Colorful hillside houses, murals, art alleys",
    blurb: "Busan's rainbow hillside village — endless photo corners, tiny galleries and viewpoints. Wear comfy shoes, it's all stairs.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Toseong Stn (Line 1) + village bus",
    price: "Free",
    must_try: true
  },
  {
    id: "haedong-yonggungsa",
    name: "Haedong Yonggungsa",
    name_kr: "해동 용궁사",
    city: "busan",
    area: "Gijang",
    category: "landmark",
    cuisine: null,
    signature: "Seaside Buddhist temple on the rocks",
    blurb: "A rare temple built right on the ocean cliffs — dramatic waves, incense and sea air. Go early to beat the crowds.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "NE Busan coast (taxi/bus)",
    price: "Free",
    must_try: false
  },
  {
    id: "gwangalli-beach",
    name: "Gwangalli Beach",
    name_kr: "광안리해수욕장",
    city: "busan",
    area: "Gwangalli",
    category: "landmark",
    cuisine: null,
    signature: "Beach with Gwangan Bridge night view, drone shows",
    blurb: "The most atmospheric city beach — cafes behind you, the lit-up Gwangan Bridge ahead. Best at night (weekend drone shows).",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "Free",
    must_try: false
  },
  {
    id: "haeundae-beach",
    name: "Haeundae Beach",
    name_kr: "해운대해수욕장",
    city: "busan",
    area: "Haeundae",
    category: "landmark",
    cuisine: null,
    signature: "Busan's famous main beach + Blueline coastal walk",
    blurb: "The classic Busan beach — wide sand, seafood nearby, and the start of the scenic Blueline Park coastal trail.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Haeundae Stn (Line 2)",
    price: "Free",
    must_try: false
  },
  {
    id: "cheongsapo-sky-capsule",
    name: "Sky Capsule (Cheongsapo)",
    name_kr: "청사포 스카이캡슐",
    city: "busan",
    area: "Cheongsapo (Haeundae)",
    category: "photo",
    cuisine: null,
    signature: "Pastel capsule ride along the coast",
    blurb: "A tiny pastel capsule that glides on old rail tracks right along the sea — pure photo magic. Book online, it sells out.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Mipo / Cheongsapo (Blueline Park)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "huinnyeoul-culture-village",
    name: "Huinnyeoul Culture Village",
    name_kr: "흰여울문화마을",
    city: "busan",
    area: "Yeongdo",
    category: "photo",
    cuisine: null,
    signature: "White cliffside houses over the sea",
    blurb: "A whitewashed village perched on a sea cliff on Yeongdo island — narrow lanes, blue water, and postcard views everywhere.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Yeongdo (taxi/bus)",
    price: "Free",
    must_try: false
  },
  {
    id: "jagalchi-market",
    name: "Jagalchi Fish Market",
    name_kr: "자갈치시장",
    city: "busan",
    area: "Nampo (Jung-gu)",
    category: "landmark",
    cuisine: null,
    signature: "Korea's largest seafood market, fresh hoe (raw fish)",
    blurb: "Busan's iconic fish market — pick your seafood downstairs and have it prepared upstairs. All seafood, naturally pork-free.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Jagalchi Stn (Line 1), exit 10",
    price: "₩₩",
    must_try: false
  }

  // ---------- TODO (next passes) ----------
  // COORDS: newly-added spots have lat/lng/place_id = null (Google resolves them by name for now).
  //         Add exact coords when convenient — needed only for the optional My Maps overview.
  // MORE:   Seoul chinese ×1 more (pork-free), a Busan korean seafood restaurant, more desserts.
  // JAPAN:  add as 3rd tab later (Tokyo? Osaka? Kyoto? Uji = matcha holy land) — ask Linda her cities.
];
