// ============================================================
//  Linda's Korea Guide — curated places
//  Add a place: copy any object below, fill the fields, done.
//  Fields you can leave null: cuisine, place_id, instagram, hours,
//  station, lat, lng (map button falls back to a name search).
//  city: "seoul" | "busan" | "gyeongju"  (gyeongju shows under the Busan tab)
//  category: matcha|sushi|japanese|chinese|korean|italian|dessert|cafe|photo|landmark
//  spice: 0 none/NA · 1 mild · 2 medium · 3 hot   (only shown for food)
//  pork_lamb_free: true safe · false contains pork/lamb · null = NA (cafe/dessert)
// ============================================================

const PLACES = [
  // ---------- SEOUL · Matcha / Dessert ----------
  {
    id: "super-matcha-seongsu",
    name: "Super Matcha Seongsu",
    name_kr: "슈퍼말차 성수",
    address: "서울 성동구 서울숲6길 19",
    city: "seoul",
    area: "Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Hand-whisked matcha latte, matcha roll cake",
    blurb: "Minimalist matcha specialist — strong, real matcha. A fan favorite and a great first stop.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5474581,
    lng: 127.0436943,
    place_id: "ChIJGz1f9SSlfDURcPrJUN2BSVs",
    instagram: "supermatcha.official",
    hours: "11:00–21:00 daily",
    station: "Seongsu Stn (Line 2), 6 min walk",
    price: "₩₩",
    must_try: true
  },
  {
    id: "cortz-yongsan",
    name: "Cortz",
    name_kr: "코르츠",
    address: "서울 용산구 백범로99길 40 102동 109호",
    city: "seoul",
    area: "Samgakji (Yongsan)",
    category: "matcha",
    cuisine: null,
    signature: "Kyoto Uji matcha latte, matcha cappuccino",
    blurb: "A specialty cafe famous among matcha lovers — Kyoto Uji matcha latte and matcha cappuccino, done properly.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.5352724,
    lng: 126.9712764,
    place_id: null,
    instagram: null,
    hours: null,
    station: "Samgakji Stn (Lines 4/6)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "oats-coffee-yongsan",
    name: "Oats Coffee",
    name_kr: "오츠커피",
    address: "서울 용산구 원효로89길 13-12",
    city: "seoul",
    area: "Namyeong (Yongsan)",
    category: "cafe",
    cuisine: null,
    signature: "Signature einspänner, matcha cream drinks, scones",
    blurb: "Yongsan's famous einspänner cafe — silky sweet cream on top. Also loved for its matcha cream drinks and scones.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.5404128,
    lng: 126.9677636,
    place_id: null,
    instagram: null,
    hours: null,
    station: "Namyeong Stn (Line 1)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "cafe-tilde-namyeong",
    name: "Cafe Tilde",
    name_kr: "틸데",
    city: "seoul",
    area: "Namyeong (Yongsan)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha cream latte, matcha bingsu (wine bar at night)",
    blurb: "Foreigners repeatedly call it the best matcha in Korea. Cafe by day, wine bar by night.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.5435969,
    lng: 126.9734246,
    place_id: "ChIJHx3sFgCjfDURpv-rTpfpVIw",
    instagram: "tilde.cafe.wine",
    hours: "12:00–23:00, closed Mon",
    station: "Namyeong Stn (Line 1)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "toroto-seongsu",
    name: "Toroto",
    name_kr: "토로토로",
    city: "seoul",
    area: "Seongsu",
    category: "dessert",
    cuisine: null,
    signature: "Strawberry matcha, tiramisu, basque cheesecake",
    blurb: "Japanese-vibe basement dessert cafe — dim, moody, and very photogenic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.538938,
    lng: 127.0564606,
    place_id: "ChIJrzUcIgClfDURsdhImQWrDk8",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "notre-don-seoulsup",
    name: "Notre Don",
    name_kr: "노트르동",
    city: "seoul",
    area: "Seoul Forest / Seongsu",
    category: "dessert",
    cuisine: null,
    signature: "Madeleines, pistachio pastries",
    blurb: "High-reputation pastry shop near Seoul Forest. Grab a box for the road.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.5473154,
    lng: 127.0400271,
    place_id: "ChIJZyWHihCjfDURiUxkfFoiQGQ",
    instagram: null,
    hours: null,
    station: "Seoul Forest Stn (Suin-Bundang)",
    price: "₩₩",
    must_try: false
  },

  // ---------- SEOUL near-suburb (Bundang / Pangyo — only if she goes south) ----------
  {
    id: "orvcha-pangyo",
    name: "Orvcha",
    name_kr: "오브차",
    city: "seoul",
    area: "Pangyo (Seongnam)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha bingsu, strawberry mochi",
    blurb: "Tatami tea-house with a calm, lab-like aesthetic. Worth it if you're already south of the river.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.3851171,
    lng: 127.1109977,
    place_id: "ChIJW8VrgMVZezURRmfNKXn7JnM",
    instagram: null,
    hours: null,
    station: "Pangyo area",
    price: "₩₩",
    must_try: false
  },
  {
    id: "daily-oasis-yatap",
    name: "Daily Oasis",
    name_kr: "데일리오아시스 분당 야탑",
    city: "seoul",
    area: "Yatap (Seongnam)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha lemonade, mango bingsu",
    blurb: "English-friendly staff — an easy, relaxed stop if you head to Bundang.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 37.410009,
    lng: 127.1300286,
    place_id: "ChIJhw3XW5mpfDURR-If-l7TMmE",
    instagram: null,
    hours: null,
    station: "Yatap Stn (Bundang Line)",
    price: "₩₩",
    must_try: false
  },

  // ---------- BUSAN · Matcha / Dessert ----------
  {
    id: "cafe-hitaro-sajik",
    name: "Cafe Hitaro",
    name_kr: "카페 히타로",
    address: "부산 동래구 사직북로13번길 42",
    city: "busan",
    area: "Sajik-dong (Dongnae)",
    category: "matcha",
    cuisine: null,
    signature: "Uji matcha latte (whisked to order), matcha shot latte, madeleine",
    blurb: "Busan's matcha holy grail — premium Uji matcha in a Japanese-house setting. 5 min from Sajik Stadium.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1926,           // TODO verify exact coords
    lng: 129.0611,
    place_id: "ChIJo32Vo2mVaDUR1fgxX99AxBY",
    instagram: null,
    hours: null,
    station: "Sajik Stn (Line 3)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "simmian-cheongsapo",
    name: "Simmian",
    name_kr: "심미안",
    address: "부산 해운대구 청사포로 128",
    city: "busan",
    area: "Cheongsapo (Haeundae)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha bingsu, matcha crepe cake, strawberry matcha latte",
    blurb: "Quiet hidden gem near the sea — sit on the floor, traditional style. Beautiful and calm.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1617136,
    lng: 129.188696,
    place_id: "ChIJPWoJM2yNaDURYDpEMm4wA4w",
    instagram: null,
    hours: null,
    station: "Cheongsapo (Sky Capsule area)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "yeonui-yanggwa-gwangalli",
    name: "Yeonui Yanggwa",
    name_kr: "연의양과 광안점",
    city: "busan",
    area: "Gwangalli",
    category: "dessert",
    cuisine: null,
    signature: "Bingsu (watermelon / mango)",
    blurb: "Fresh-fruit bingsu a short walk from Gwangalli beach. Perfect summer cool-down.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: 35.1574301,
    lng: 129.1217163,
    place_id: "ChIJ_XOb-2DtaDURfxJJsIpcHdI",
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "deokmi-atelier-gwangalli",
    name: "Deokmi Atelier",
    name_kr: "덕미 아틀리에",
    city: "busan",
    area: "Gwangalli",
    category: "cafe",
    cuisine: null,
    signature: "Sandwiches, tea",
    blurb: "Charming 4.9-rated brunch spot near Gwangalli, with resident cats. Heads up: jambon items contain ham — ask for a pork-free option.",
    spice: 0,
    pork_lamb_free: false,   // jambon = ham; ask staff for pork-free choice
    photo_spot: true,
    lat: 35.1564665,
    lng: 129.1206828,
    place_id: "ChIJ20yPvNntaDURwR9_3bONaeE",
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ---------- GYEONGJU (Busan daytrip — shows under Busan tab) ----------
  {
    id: "noka-gyeongju",
    name: "NOKA",
    name_kr: "노카 녹아",
    city: "gyeongju",
    area: "Hwangnam-dong, Gyeongju",
    category: "dessert",
    cuisine: null,
    signature: "Matcha gelato (pick your sweetness / bitterness), hojicha",
    blurb: "A matcha ice-cream destination in old-town Gyeongju — you choose how sweet or bitter. Worth the daytrip.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.8360948,
    lng: 129.2117779,
    place_id: "ChIJ_z1MHVVPZjUR5F-zYNhCJDA",
    instagram: null,
    hours: null,
    station: "Gyeongju (daytrip from Busan)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Sushi (Linda loves sushi — all pork-free, spice 0) ==========
  {
    id: "mine-sushi-yeoksam",
    name: "Mine Sushi",
    name_kr: "미네 스시",
    city: "seoul",
    area: "Yeoksam (Gangnam)",
    category: "sushi",
    cuisine: "japanese",
    signature: "Counter omakase, Edomae nigiri",
    blurb: "Widely called Seoul's best traditional Edomae sushi — sit at the counter for the omakase. A real treat for a sushi lover.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,   // TODO verify coords
    instagram: null,
    hours: null,
    station: "Yeoksam Stn (Line 2)",
    price: "₩₩₩",
    must_try: true
  },
  {
    id: "gatten-sushi-gangnam",
    name: "Gatten Sushi",
    name_kr: "갓덴스시 강남",
    city: "seoul",
    area: "Gangnam",
    category: "sushi",
    cuisine: "japanese",
    signature: "Conveyor-belt nigiri, fresh & affordable",
    blurb: "Fun, casual conveyor-belt sushi — grab what looks good, easy on the wallet, no reservation needed.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Gangnam Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Italian ==========
  {
    id: "zio-cucina-ikseon",
    name: "Zio Cucina Ikseon",
    name_kr: "지오쿠치나 익선",
    city: "seoul",
    area: "Ikseon-dong",
    category: "italian",
    cuisine: "italian",
    signature: "Four-cheese pizza, porcini pasta, brick-oven pizza",
    blurb: "Cozy Italian tucked in Ikseon-dong's pretty hanok alleys. Plenty of cheese/veggie/seafood options — just skip the pancetta pastas.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Jongno 3-ga Stn (Lines 1/3/5)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "kitchen-485-hongdae",
    name: "Kitchen 485",
    name_kr: "키친485",
    city: "seoul",
    area: "Hongdae",
    category: "italian",
    cuisine: "italian",
    signature: "Spinach tagliatelle, mushroom sauce, handmade pizza",
    blurb: "A Hongdae favorite for authentic pizza and fresh pasta — the veggie-forward signatures are naturally pork-free.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Korean (no-pork picks — chicken / beef / spice-tagged) ==========
  {
    id: "tosokchon-samgyetang",
    name: "Tosokchon Samgyetang",
    name_kr: "토속촌 삼계탕",
    city: "seoul",
    area: "Jongno (near Gyeongbokgung)",
    category: "korean",
    cuisine: "korean",
    signature: "Samgyetang — ginseng chicken soup (not spicy)",
    blurb: "The famous ginseng-chicken soup right by Gyeongbokgung — whole young chicken stuffed with rice, garlic, jujube. Chicken only, zero spice. Perfect after the palace.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Gyeongbokgung Stn (Line 3)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "byeokje-galbi",
    name: "Byeokje Galbi",
    name_kr: "벽제갈비",
    city: "seoul",
    area: "Songpa",
    category: "korean",
    cuisine: "korean",
    signature: "Premium beef galbi (Korean BBQ), galbi-tang",
    blurb: "High-end beef-only Korean BBQ — no pork on the grill here. A splurge, but a legendary one.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Munjeong Stn (Line 8)",
    price: "₩₩₩",
    must_try: false
  },
  {
    id: "yoogane-dakgalbi-myeongdong",
    name: "Yoogane Dak-galbi",
    name_kr: "유가네 닭갈비 명동",
    city: "seoul",
    area: "Myeongdong",
    category: "korean",
    cuisine: "korean",
    signature: "Dak-galbi — stir-fried spicy chicken",
    blurb: "Sizzling stir-fried chicken with rice — tourist-friendly with English menus. Medium spicy; you can ask them to tone it down.",
    spice: 2,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Myeongdong Stn (Line 4)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Chinese (pork-risky cuisine — flagged to be safe) ==========
  {
    id: "madam-ming-yeouido",
    name: "Madam Ming",
    name_kr: "마담밍",
    city: "seoul",
    area: "Yeouido",
    category: "chinese",
    cuisine: "chinese",
    signature: "Jjamppong naengmyeon (cold seafood noodles, spice 1–5)",
    blurb: "A 20-year specialist in cold seafood jjamppong noodles — you pick the spice level. Seafood-based, but Korean-Chinese kitchens use pork, so ask for the no-pork/seafood option.",
    spice: 2,
    pork_lamb_free: false,   // Korean-Chinese: assume pork unless confirmed — ask staff
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Yeouido Stn (Lines 5/9)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Landmarks / Photo spots ==========
  {
    id: "gyeongbokgung",
    name: "Gyeongbokgung Palace",
    name_kr: "경복궁",
    city: "seoul",
    area: "Jongno",
    category: "landmark",
    cuisine: null,
    signature: "Main royal palace, changing-of-the-guard, hanbok photos",
    blurb: "Seoul's grand Joseon-era palace. Rent a hanbok nearby to get in free and take gorgeous photos. Closed Tuesdays.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: "09:00–18:00, closed Tue",
    station: "Gyeongbokgung Stn (Line 3), exit 5",
    price: "₩",
    must_try: true
  },
  {
    id: "bukchon-hanok-village",
    name: "Bukchon Hanok Village",
    name_kr: "북촌한옥마을",
    city: "seoul",
    area: "Jongno",
    category: "photo",
    cuisine: null,
    signature: "Traditional hanok alleyways, rooftop views",
    blurb: "Quiet lanes of restored hanok houses between the palaces — the classic Seoul postcard shot. Keep your voice down; people live here.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Anguk Stn (Line 3), exit 2",
    price: "Free",
    must_try: false
  },
  {
    id: "ikseon-dong",
    name: "Ikseon-dong Hanok Street",
    name_kr: "익선동",
    city: "seoul",
    area: "Jongno",
    category: "photo",
    cuisine: null,
    signature: "Trendy hanok cafes, dessert & photo alleys",
    blurb: "A maze of old hanok turned into cute cafes, dessert shops and boutiques — very photogenic, great for an afternoon wander.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Jongno 3-ga Stn (Lines 1/3/5)",
    price: "Free",
    must_try: false
  },
  {
    id: "seoul-forest",
    name: "Seoul Forest",
    name_kr: "서울숲",
    city: "seoul",
    area: "Seongsu",
    category: "landmark",
    cuisine: null,
    signature: "Big city park, deer enclosure, tree-lined paths",
    blurb: "A leafy park right by the Seongsu cafes — perfect to pair with your matcha crawl. Lovely light in the late afternoon.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seoul Forest Stn (Suin-Bundang)",
    price: "Free",
    must_try: false
  },
  {
    id: "yeouido-hangang-park",
    name: "Yeouido Hangang Park",
    name_kr: "여의도 한강공원",
    city: "seoul",
    area: "Yeouido",
    category: "landmark",
    cuisine: null,
    signature: "Han River picnic spot, sunset, night views",
    blurb: "Grab a mat and some snacks and watch the sun set over the Han River — a favorite local evening. Instant-ramyeon machines on site.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Yeouinaru Stn (Line 5), exit 2/3",
    price: "Free",
    must_try: false
  },
  {
    id: "namsan-tower",
    name: "N Seoul Tower (Namsan)",
    name_kr: "남산서울타워",
    city: "seoul",
    area: "Yongsan",
    category: "landmark",
    cuisine: null,
    signature: "City-wide views, cable car, night lights",
    blurb: "Ride the cable car up Namsan for the best panoramic view of Seoul — especially magical after dark.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Myeongdong Stn (Line 4) + cable car",
    price: "₩₩",
    must_try: false
  },

  // ========== BUSAN · Sushi / Japanese ==========
  {
    id: "sushi-iruka-haeundae",
    name: "Sushi Iruka",
    name_kr: "스시 이루카",
    city: "busan",
    area: "Marine City (Haeundae)",
    category: "sushi",
    cuisine: "japanese",
    signature: "Edomae omakase, Japanese sake pairing",
    blurb: "Calm, high-quality Edomae sushi in Marine City — fresh daily catch and a quiet counter. Book ahead.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Marine City (Haeundae)",
    price: "₩₩₩",
    must_try: false
  },
  {
    id: "sushi-yama-haeundae",
    name: "Sushi Yama",
    name_kr: "스시야마 해운대",
    city: "busan",
    area: "Jung-dong (Haeundae)",
    category: "sushi",
    cuisine: "japanese",
    signature: "Conveyor-belt sushi, fresh & good value",
    blurb: "Popular casual conveyor-belt sushi near Haeundae — reliable, cheap and quick when you just want a plate of nigiri.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Haeundae Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ========== BUSAN · Landmarks / Photo spots ==========
  {
    id: "gamcheon-culture-village",
    name: "Gamcheon Culture Village",
    name_kr: "감천문화마을",
    city: "busan",
    area: "Saha-gu",
    category: "photo",
    cuisine: null,
    signature: "Colorful hillside houses, murals, art alleys",
    blurb: "Busan's rainbow hillside village — endless photo corners, tiny galleries and viewpoints. Wear comfy shoes, it's all stairs.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Toseong Stn (Line 1) + village bus",
    price: "Free",
    must_try: true
  },
  {
    id: "haedong-yonggungsa",
    name: "Haedong Yonggungsa",
    name_kr: "해동 용궁사",
    city: "busan",
    area: "Gijang",
    category: "landmark",
    cuisine: null,
    signature: "Seaside Buddhist temple on the rocks",
    blurb: "A rare temple built right on the ocean cliffs — dramatic waves, incense and sea air. Go early to beat the crowds.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "NE Busan coast (taxi/bus)",
    price: "Free",
    must_try: false
  },
  {
    id: "gwangalli-beach",
    name: "Gwangalli Beach",
    name_kr: "광안리해수욕장",
    city: "busan",
    area: "Gwangalli",
    category: "landmark",
    cuisine: null,
    signature: "Beach with Gwangan Bridge night view, drone shows",
    blurb: "The most atmospheric city beach — cafes behind you, the lit-up Gwangan Bridge ahead. Best at night (weekend drone shows).",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "Free",
    must_try: false
  },
  {
    id: "haeundae-beach",
    name: "Haeundae Beach",
    name_kr: "해운대해수욕장",
    city: "busan",
    area: "Haeundae",
    category: "landmark",
    cuisine: null,
    signature: "Busan's famous main beach + Blueline coastal walk",
    blurb: "The classic Busan beach — wide sand, seafood nearby, and the start of the scenic Blueline Park coastal trail.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Haeundae Stn (Line 2)",
    price: "Free",
    must_try: false
  },
  {
    id: "cheongsapo-sky-capsule",
    name: "Sky Capsule (Cheongsapo)",
    name_kr: "청사포 스카이캡슐",
    city: "busan",
    area: "Cheongsapo (Haeundae)",
    category: "photo",
    cuisine: null,
    signature: "Pastel capsule ride along the coast",
    blurb: "A tiny pastel capsule that glides on old rail tracks right along the sea — pure photo magic. Book online, it sells out.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Mipo / Cheongsapo (Blueline Park)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "huinnyeoul-culture-village",
    name: "Huinnyeoul Culture Village",
    name_kr: "흰여울문화마을",
    city: "busan",
    area: "Yeongdo",
    category: "photo",
    cuisine: null,
    signature: "White cliffside houses over the sea",
    blurb: "A whitewashed village perched on a sea cliff on Yeongdo island — narrow lanes, blue water, and postcard views everywhere.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Yeongdo (taxi/bus)",
    price: "Free",
    must_try: false
  },
  {
    id: "jagalchi-market",
    name: "Jagalchi Fish Market",
    name_kr: "자갈치시장",
    city: "busan",
    area: "Nampo (Jung-gu)",
    category: "landmark",
    cuisine: null,
    signature: "Korea's largest seafood market, fresh hoe (raw fish)",
    blurb: "Busan's iconic fish market — pick your seafood downstairs and have it prepared upstairs. All seafood, naturally pork-free.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Jagalchi Stn (Line 1), exit 10",
    price: "₩₩",
    must_try: false
  },

  // ========== Shops / 소품샵 (design & stationery select-shops) ==========
  {
    id: "object-seongsu",
    name: "Object",
    name_kr: "오브젝트 성수",
    city: "seoul",
    area: "Seongsu",
    category: "shop",
    cuisine: null,
    signature: "Design goods, stationery, ceramics, vintage",
    blurb: "A beloved Korean lifestyle select-shop — stationery, ceramics and quirky homeware over several floors. Perfect for gifts.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "point-of-view-seongsu",
    name: "Point of View",
    name_kr: "포인트오브뷰 성수",
    city: "seoul",
    area: "Seongsu",
    category: "shop",
    cuisine: null,
    signature: "Curated stationery & desk objects",
    blurb: "A dreamy, museum-like stationery shop — pens, paper and little treasures beautifully displayed. A photo favorite.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "mmmg-hannam",
    name: "MMMG (Millimeter Milligram)",
    name_kr: "밀리미터 밀리그람 한남",
    city: "seoul",
    area: "Hannam",
    category: "shop",
    cuisine: null,
    signature: "Design stationery, notebooks, totes & bags",
    blurb: "The MMMG flagship — minimalist Korean design goods, notebooks and totes. Easy to pair with a Hannam cafe stroll.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Hannam / Itaewon area",
    price: "₩₩",
    must_try: false
  },
  {
    id: "object-seomyeon",
    name: "Object",
    name_kr: "오브젝트 서면",
    city: "busan",
    area: "Seomyeon",
    category: "shop",
    cuisine: null,
    signature: "Design goods & souvenirs",
    blurb: "The Busan branch of the Object select-shop — design goods and cute souvenirs in the heart of Seomyeon.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seomyeon Stn (Lines 1/2)",
    price: "₩₩",
    must_try: false
  },

  // ========== Fashion & Vintage (옷가게 / 빈티지) ==========
  {
    id: "dongmyo-flea-market",
    name: "Dongmyo Flea Market",
    name_kr: "동묘 벼룩시장",
    city: "seoul",
    area: "Jongno (Dongmyo)",
    category: "fashion",
    cuisine: null,
    signature: "Vintage & thrift clothing, retro treasure-hunting",
    blurb: "Seoul's famous flea market — racks of cheap vintage and retro finds. Grungy, lively and very local. Come to dig.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Dongmyo Stn (Lines 1/6)",
    price: "₩",
    must_try: false
  },
  {
    id: "ader-error-seongsu",
    name: "ADER Error (Seongsu)",
    name_kr: "아더에러 성수",
    city: "seoul",
    area: "Seongsu",
    category: "fashion",
    cuisine: null,
    signature: "Cult Korean streetwear, art-installation store",
    blurb: "The flagship of cult label Ader Error — surreal interiors as much as clothes. A photo playground even if you don't buy.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "gentle-monster-haus-dosan",
    name: "Gentle Monster (Haus Dosan)",
    name_kr: "젠틀몬스터 하우스 도산",
    city: "seoul",
    area: "Sinsa (Apgujeong)",
    category: "fashion",
    cuisine: null,
    signature: "Avant-garde eyewear/fashion + Nudake dessert",
    blurb: "A jaw-dropping concept building: Gentle Monster eyewear, Tamburins scents, and Nudake's sculptural desserts. Free art-gallery vibes.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Apgujeong / Sinsa area",
    price: "₩₩",
    must_try: false
  },
  {
    id: "musinsa-standard-hongdae",
    name: "Musinsa Standard (Hongdae)",
    name_kr: "무신사 스탠다드 홍대",
    city: "seoul",
    area: "Hongdae",
    category: "fashion",
    cuisine: null,
    signature: "Popular affordable Korean fashion flagship",
    blurb: "The flagship of Korea's biggest fashion platform — well-priced basics and trend pieces across several floors.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "gwangbok-fashion-street",
    name: "Gwangbok-dong Fashion Street",
    name_kr: "광복동 패션거리",
    city: "busan",
    area: "Nampo (Jung-gu)",
    category: "fashion",
    cuisine: null,
    signature: "Busan's main shopping street — brands & boutiques",
    blurb: "Busan's busiest shopping street near Nampo — Korean brands, boutiques and street food all in one lively walk.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Nampo Stn (Line 1)",
    price: "₩₩",
    must_try: false
  },

  // ========== Self-photo booths / 인생네컷 (a fun Korea keepsake — category: photo) ==========
  {
    id: "life4cut-hongdae",
    name: "Life Four Cuts",
    name_kr: "인생네컷 홍대",
    city: "seoul",
    area: "Hongdae (& citywide)",
    category: "photo",
    cuisine: null,
    signature: "Retro self-photo booth — instant 4-cut film strips",
    blurb: "Korea's iconic self-photo booth — pile in, pose with props, and print instant 4-cut strips. A must-do keepsake. Branches everywhere (Hongdae, Myeongdong, Busan too).",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩",
    must_try: false
  },
  {
    id: "photoism-gangnam",
    name: "Photoism",
    name_kr: "포토이즘 박스 강남",
    city: "seoul",
    area: "Gangnam (& citywide)",
    category: "photo",
    cuisine: null,
    signature: "Trendy self-photo studio, fun frames & props",
    blurb: "A sleeker self-photo studio chain with stylish frames and celeb/AI options. Great rainy-day activity.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Gangnam Stn (Line 2)",
    price: "₩",
    must_try: false
  },
  {
    id: "haru-film-hongdae",
    name: "Haru Film",
    name_kr: "하루필름 홍대",
    city: "seoul",
    area: "Hongdae (& citywide)",
    category: "photo",
    cuisine: null,
    signature: "Film-look self-photo booth, warm aesthetic filters",
    blurb: "A self-photo booth loved for its warm, film-toned look — the prettiest strips of the bunch.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩",
    must_try: false
  },
  {
    id: "photoism-seomyeon",
    name: "Photoism",
    name_kr: "포토이즘 서면",
    city: "busan",
    area: "Seomyeon",
    category: "photo",
    cuisine: null,
    signature: "Self-photo booth — instant 4-cut strips",
    blurb: "Grab a fun 4-cut photo keepsake in central Busan — same self-photo-booth craze, Seomyeon branch.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seomyeon Stn (Lines 1/2)",
    price: "₩",
    must_try: false
  },

  // ========== SEOUL · Matcha (V2 verified batch) ==========
  {
    id: "sannoru-samseong",
    name: "Sannoru",
    name_kr: "산노루 삼성점",
    address: "서울 강남구 삼성로122길 35",
    city: "seoul",
    area: "Samseong (Gangnam)",
    category: "matcha",
    cuisine: null,
    signature: "Jeju-grown tea, pick your strength (3g / 6g) — matcha latte, matcha pound cake",
    blurb: "A serious Jeju-tea specialist where you choose the matcha concentration — a real matcha-fan's spot.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Samseong / Cheongdam area (Lines 2/7)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "maetcha-myeongdong",
    name: "Maetcha",
    name_kr: "맷차 명동본점",
    address: "서울 중구 명동9길 17",
    city: "seoul",
    area: "Myeongdong",
    category: "matcha",
    cuisine: null,
    signature: "Stone-milled matcha — matcha espresso, matcha milk tea",
    blurb: "Matcha ground fresh on a stone mill — deep, grassy and intense. Central and easy to reach.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Myeongdong Stn (Line 4)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "tea-nomad-mapo",
    name: "Tea Nomad",
    name_kr: "티노마드",
    address: "서울 마포구 포은로 112",
    city: "seoul",
    area: "Mangwon (Mapo)",
    category: "matcha",
    cuisine: null,
    signature: "Reservation-only hanok teahouse — matcha latte tea set, chabing (tea bingsu)",
    blurb: "A serene, reservation-only hanok tea house — settle in for a proper matcha tea set. Book ahead.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Mapo (Mangwon / Hapjeong area)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "town-pond-euljiro",
    name: "Town Pond",
    name_kr: "타운폰드",
    city: "seoul",
    area: "Euljiro / Myeongdong",
    category: "matcha",
    cuisine: null,
    signature: "Ceremonial-style matcha & matcha sparkling",
    blurb: "Proper dado (tea-ceremony) matcha, plus a refreshing matcha sparkling — a modern take in central Seoul.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Euljiro 3-ga Stn (Lines 2/3)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "cafe-j-seongsu",
    name: "Cafe J",
    name_kr: "카페제이 성수",
    city: "seoul",
    area: "Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Premium Kyoto matcha — Kyoto matcha latte, matcha tiramisu",
    blurb: "Kyoto-sourced matcha done richly — the matcha tiramisu is the one to get.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "specter-seochon",
    name: "Specter",
    name_kr: "스펙터",
    address: "서울 종로구 필운대로6길 23-1",
    city: "seoul",
    area: "Seochon (Jongno)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha flat white in a Seochon hanok",
    blurb: "A calm hanok cafe in pretty Seochon, right by the palace — the matcha flat white is the signature.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Gyeongbokgung Stn (Line 3)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "5to7-seoulsup",
    name: "5to7",
    name_kr: "5to7 서울숲",
    address: "서울 성동구 서울숲2길 44-13",
    city: "seoul",
    area: "Seoul Forest / Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Handmade matcha cream soufflé — matcha soufflé pancakes",
    blurb: "Famous for jiggly matcha soufflé pancakes with matcha cream near Seoul Forest. Worth the wait.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seoul Forest Stn (Suin-Bundang)",
    price: "₩₩",
    must_try: false
  },

  // ========== BUSAN · Matcha (V2 verified batch) ==========
  {
    id: "kurumi-dongnae",
    name: "Kurumi Confectionery",
    name_kr: "쿠루미과자점",
    address: "부산 동래구 온천천로 71",
    city: "busan",
    area: "Dongnae (Oncheonjang)",
    category: "matcha",
    cuisine: null,
    signature: "Bakery must-visit — Jeju matcha patbingsu, baked sweets",
    blurb: "A beloved Busan bakery and bingsu stop — the Jeju matcha patbingsu is the pilgrimage order.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Oncheonjang Stn (Line 1)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "oson-1209-haeundae",
    name: "Oson 1209",
    name_kr: "오손1209",
    address: "부산 해운대구 우동1로38번길 11",
    city: "busan",
    area: "U-dong (Haeundae)",
    category: "matcha",
    cuisine: null,
    signature: "Signature matcha mont blanc",
    blurb: "A tiny specialist for one perfect thing — the matcha mont blanc. Get there early.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Haeundae area (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "haraneko-haeundae",
    name: "Haraneko",
    name_kr: "하라네코",
    address: "부산 해운대구 우동1로38번가길 19",
    city: "busan",
    area: "U-dong (Haeundae)",
    category: "matcha",
    cuisine: null,
    signature: "Cozy Japanese-style space — matcha milk, matcha madeleine & affogato",
    blurb: "A sweet little Japanese-vibe cafe near Haeundae — matcha milk and matcha madeleines. Very photogenic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Haeundae area (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "parker-jeonpo",
    name: "Parker",
    name_kr: "파커 전포",
    address: "부산 부산진구 전포대로210번길 24",
    city: "busan",
    area: "Jeonpo (Busanjin)",
    category: "matcha",
    cuisine: null,
    signature: "Jeonpo cafe-street favorite — matcha latte, seasonal desserts",
    blurb: "A solid stop on Busan's trendy Jeonpo cafe street — matcha latte with seasonal sweets.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Jeonpo Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ========== SEOUL · Matcha (tea-lover verified batch) ==========
  {
    id: "teastory-seochon",
    name: "Teastory",
    name_kr: "티스토리 서촌",
    address: "서울 종로구 자하문로10길 22",
    city: "seoul",
    area: "Seochon (Jongno)",
    category: "matcha",
    cuisine: null,
    signature: "Hand-whisked premium matcha, matcha ice cream + monaka",
    blurb: "A hanok tea house rooted in traditional tea ceremony — premium matcha whisked to order, with a lovely matcha ice cream & monaka pairing.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Gyeongbokgung Stn (Line 3)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "gelateria-dodo-seongsu",
    name: "Gelateria Dodo",
    name_kr: "젤라떼리아 도도 성수",
    address: "서울 성동구 서울숲2길 18-11",
    city: "seoul",
    area: "Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Handmade matcha gelato across intensity levels",
    blurb: "Bittersweet matcha gelato in varied concentrations — very highly rated among dessert lovers.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "cafe-gabaedo",
    name: "Cafe Gabaedo",
    name_kr: "카페 가배도",
    address: "서울 종로구 북촌로5길 56",
    city: "seoul",
    area: "Sinsa / Samcheong (multiple branches)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha tiramisu, rich matcha latte",
    blurb: "A moody, atmospheric cafe consistently praised for its soft matcha-cream tiramisu and deep matcha latte.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Sinsa (Line 3) / Anguk (Line 3)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "achieight-yongsan",
    name: "Archiet",
    name_kr: "아키에이트 용산",
    address: "서울 용산구 한강대로48길 17-6",
    city: "seoul",
    area: "Yongsan",
    category: "matcha",
    cuisine: null,
    signature: "Clean-textured matcha latte, matcha-ganache original dessert",
    blurb: "A verified Yongsan cafe with a crisp, clean matcha latte and a distinctive matcha-ganache dessert.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Yongsan area",
    price: "₩₩",
    must_try: false
  },
  {
    id: "matchacha-seoulsup",
    name: "Matchacha",
    name_kr: "맛차차 서울숲",
    address: "서울 성동구 서울숲2길 18-11",
    city: "seoul",
    area: "Seoul Forest / Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Classic hand-whisked matcha + dasik (tea sweets)",
    blurb: "A calming tea house looking onto Seoul Forest — classic matcha whisked the traditional way, served with dasik.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seoul Forest Stn (Suin-Bundang)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "moovmov-seongsu",
    name: "Moovmov",
    name_kr: "무브모브 성수",
    city: "seoul",
    area: "Seongsu",
    category: "matcha",
    cuisine: null,
    signature: "Dense matcha terrine, matcha cream latte, media-art space",
    blurb: "A thick, fudgy matcha terrine and matcha cream latte in a sleek media-art space — a Seongsu crowd-pleaser.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "bayerische-mangwon",
    name: "Bayerische",
    name_kr: "바이어리셔 망원",
    city: "seoul",
    area: "Mangwon (Mapo)",
    category: "matcha",
    cuisine: null,
    signature: "Deep-bitter handmade matcha terrine, matcha affogato",
    blurb: "A Mangwon favorite with a devoted following — bittersweet handmade matcha terrine and matcha affogato. (German name — a little hello from home!)",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Mangwon Stn (Line 6)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "long-vacation-yeonnam",
    name: "Long Vacation",
    name_kr: "롱베케이션 연남",
    city: "seoul",
    area: "Yeonnam (Mapo)",
    category: "matcha",
    cuisine: null,
    signature: "Silky dessert pudding + rich matcha latte",
    blurb: "Word-of-mouth loved for its wobbly pudding paired with a well-balanced, rich matcha latte in Yeonnam.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2) / Gyeongui line",
    price: "₩₩",
    must_try: false
  },

  // ========== BUSAN · Matcha (tea-lover verified batch) ==========
  {
    id: "suwolgyeonghwa-songjeong",
    name: "Suwolgyeonghwa",
    name_kr: "수월경화 송정",
    address: "부산 해운대구 송정구덕포길 6",
    city: "busan",
    area: "Songjeong (Haeundae)",
    category: "matcha",
    cuisine: null,
    signature: "Ocean-view premium matcha with Korean sweets platter",
    blurb: "A healing spot with sea views — premium matcha served alongside a pretty Korean sweets platter. Very high satisfaction.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Songjeong (Haeundae, Line 2 + taxi)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "noka-jeonpo",
    name: "Noka (Jeonpo)",
    name_kr: "녹아 전포",
    address: "부산 부산진구 서전로37번길 26",
    city: "busan",
    area: "Jeonpo (Busanjin)",
    category: "matcha",
    cuisine: null,
    signature: "Matcha gelato & bingsu, pick intensity level 1–4",
    blurb: "A matcha gelato & bingsu specialist where you choose the bitterness from 1 to 4 — a must for those who like it strong.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Jeonpo Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "yeongyeongjae-nampo",
    name: "Yeongyeongjae",
    name_kr: "연경재 남포",
    address: "부산 중구 중앙대로41번길 3",
    city: "busan",
    area: "Nampo (Jung-gu)",
    category: "matcha",
    cuisine: null,
    signature: "Roof-tile-shaped matcha mousse cake, deep matcha drinks",
    blurb: "An atmospheric old-town tea house famous for its Korean roof-tile-shaped matcha mousse cake and deep matcha drinks.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Nampo Stn (Line 1)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "mochi-flag-haeundae",
    name: "Mochi Flag",
    name_kr: "모치플래그 해리단길",
    address: "부산 해운대구 우동1로38번가길 15",
    city: "busan",
    area: "Haridan-gil (Haeundae)",
    category: "matcha",
    cuisine: null,
    signature: "Chewy matcha mochi desserts, matcha pasteur latte",
    blurb: "A Haridan-gil hit for chewy matcha mochi and a distinctive matcha 'pasteur' latte — handmade and different.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: false,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Haeundae Stn (Line 2), Haridan-gil",
    price: "₩₩",
    must_try: false
  },
  {
    id: "yehwa-chodang-dalmaji",
    name: "Yehwa Chodang",
    name_kr: "예화초당 달맞이길",
    city: "busan",
    area: "Dalmaji-gil (Haeundae)",
    category: "matcha",
    cuisine: null,
    signature: "Artisan matcha tasting, hand-whisked (격불) tea ceremony",
    blurb: "A multi-generation traditional matcha specialist on Dalmaji-gil — a deep, premium tasting and hand-whisked tea-ceremony experience. A treat for a real matcha fan.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Dalmaji-gil (Haeundae, Line 2 + taxi)",
    price: "₩₩₩",
    must_try: true
  },
  {
    id: "ochoryang-choryang",
    name: "Ochoryang",
    name_kr: "오초량 초량",
    address: "부산 동구 고관로13번길 53",
    city: "busan",
    area: "Choryang (Dong-gu)",
    category: "matcha",
    cuisine: null,
    signature: "High-quality matcha & traditional tea in a modern hanok",
    blurb: "A tranquil early-modern hanok with a Japanese garden — the perfect setting to savor quality matcha and traditional tea.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Choryang Stn (Line 1)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "nudake-seongsu",
    name: "Nudake",
    name_kr: "누데이크 성수",
    address: "서울 성동구 성수이로7길 26",
    city: "seoul",
    area: "Seongsu",
    category: "dessert",
    cuisine: null,
    signature: "'Peak' matcha lava cake",
    blurb: "The artful dessert house (by Gentle Monster) — the signature 'Peak' matcha lava cake is a showstopper.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: null, lng: null, place_id: null,
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },

  // ========== Gejang · marinated raw crab (Linda asked for 게장 — crab, pork-free) ==========
  {
    id: "odarijip-gejang",
    name: "Odarijip Ganjang Gejang",
    name_kr: "오다리집 간장게장",
    address: "서울 중구 명동8나길 28",
    city: "seoul",
    area: "Myeongdong",
    category: "korean",
    cuisine: "korean",
    signature: "Soy-marinated raw crab (ganjang-gejang), spicy crab too",
    blurb: "A Myeongdong institution (6,800+ reviews) for ganjang-gejang — soy-marinated raw crab you spoon over warm rice. The soy version is not spicy; there's a spicy (yangnyeom) crab too. All crab, no pork.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: 37.5613796,
    lng: 126.9834141,
    place_id: "ChIJNbhaHPGifDURDCGKakYKwXw",
    instagram: null,
    hours: null,
    station: "Myeongdong Stn (Line 4)",
    price: "₩₩₩",
    must_try: true
  },
  {
    id: "sura-gejang-myeongdong",
    name: "Sura Gejang",
    name_kr: "수라게장 명동본점",
    address: "서울 중구 명동10길 18",
    city: "seoul",
    area: "Myeongdong",
    category: "korean",
    cuisine: "korean",
    signature: "Soy-marinated crab, spicy marinated crab",
    blurb: "Another beloved Myeongdong crab house — silky soy-marinated crab plus a spicy version. A proper 'rice thief.' Crab only, pork-free.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: 37.5628447,
    lng: 126.9853143,
    place_id: "ChIJK0AARp-jfDURZN60tE_e0O0",
    instagram: null,
    hours: null,
    station: "Myeongdong Stn (Line 4)",
    price: "₩₩₩",
    must_try: false
  },
  {
    id: "sinsa-kkotgedang-haeundae",
    name: "Sinsa Kkotgedang (Haeundae)",
    name_kr: "신사꽃게당 해운대점",
    city: "busan",
    area: "Haeundae",
    category: "korean",
    cuisine: "korean",
    signature: "Marinated crab set (soy + spicy), foreigner-friendly",
    blurb: "Haeundae's go-to marinated-crab spot, used to overseas guests. Mild soy crab plus a spicy option, with lots of side dishes. All crab, pork-free.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: 35.1597081,
    lng: 129.1595155,
    place_id: "ChIJ8_GPyHeNaDURha_9MZpINOY",
    instagram: null,
    hours: null,
    station: "Haeundae area (Line 2)",
    price: "₩₩₩",
    must_try: false
  },
  {
    id: "mipojip-haeundae",
    name: "Mipojip",
    name_kr: "미포집 해운대본점",
    address: "부산 해운대구 달맞이길62번길 3",
    city: "busan",
    area: "Dalmaji-gil (Haeundae)",
    category: "korean",
    cuisine: "korean",
    signature: "Marinated-crab feast with endless side dishes",
    blurb: "A Dalmaji-hill classic famous for its crab spread — soy and spicy marinated crab with a table full of banchan. Crab, pork-free.",
    spice: 0,
    pork_lamb_free: true,
    photo_spot: false,
    lat: 35.160751,
    lng: 129.1714544,
    place_id: "ChIJmY-JGj-NaDUREWEsi5cjUjw",
    instagram: null,
    hours: null,
    station: "Jung-dong (Haeundae, Line 2)",
    price: "₩₩₩",
    must_try: false
  },

  {
    id: "wiggle-wiggle-dosan",
    name: "Wiggle Wiggle (Dosan)",
    name_kr: "위글위글집 도산",
    address: "서울특별시 강남구 언주로168길 31",
    city: "seoul",
    area: "Dosan (Apgujeong)",
    category: "shop",
    cuisine: null,
    signature: "Candy-colored design goods & gifts",
    blurb: "Korea's playful design brand — a rainbow shop of stationery, homeware and gifts. Peak cute, very photogenic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5260826,
    lng: 127.0362786,
    place_id: "ChIJs7zCMGmjfDUR9Ihzyq-d5g0",
    instagram: null,
    hours: null,
    station: "Apgujeong Rodeo Stn",
    price: "₩₩",
    must_try: true
  },
  {
    id: "wave-on-coffee-gijang",
    name: "Wave On Coffee",
    name_kr: "웨이브온 커피",
    address: "부산광역시 기장군 해맞이로 286",
    city: "busan",
    area: "Gijang",
    category: "cafe",
    cuisine: null,
    signature: "Cliff-top ocean-view coffee",
    blurb: "A dramatic architectural cafe on the cliffs of Gijang — worth the trip for the sea view alone.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.3223106,
    lng: 129.2696854,
    place_id: "ChIJ-Q0IE9KGaDUR-hnQ05hxW4g",
    instagram: null,
    hours: null,
    station: "Gijang (taxi/bus)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "onion-seongsu",
    name: "Onion Seongsu",
    name_kr: "어니언 성수점",
    address: "서울특별시 성동구 아차산로9길 8",
    city: "seoul",
    area: "Seongsu",
    category: "cafe",
    cuisine: null,
    signature: "Pandoro, pastries in a raw-concrete space",
    blurb: "The cafe that defined the Seongsu look — bare concrete, pastries piled high, and the famous snow-sugar pandoro. Go early.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5447328,
    lng: 127.0582091,
    place_id: "ChIJHb1ypJWkfDURb2d4XCjLluM",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "daelim-changgo-seongsu",
    name: "Daelim Changgo Gallery",
    name_kr: "성수동 대림창고 갤러리",
    address: "서울특별시 성동구 성수이로 78",
    city: "seoul",
    area: "Seongsu",
    category: "cafe",
    cuisine: null,
    signature: "Warehouse gallery-cafe",
    blurb: "A converted warehouse gallery-cafe — cavernous, artsy and endlessly photogenic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5418384,
    lng: 127.0564636,
    place_id: "ChIJi_M445OkfDURBV_ePY2qCHo",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "park-yeongdo",
    name: "P.ARK",
    name_kr: "피아크",
    address: "부산광역시 영도구 해양로195번길 180",
    city: "busan",
    area: "Yeongdo",
    category: "cafe",
    cuisine: null,
    signature: "Giant seaside bakery-cafe",
    blurb: "A huge seaside bakery-cafe on Yeongdo with floor-to-ceiling ocean views. Grab bread and a window seat.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.0862015,
    lng: 129.076151,
    place_id: "ChIJ_b5fELXvaDURlKkKhfM0WNk",
    instagram: null,
    hours: null,
    station: "Yeongdo (taxi/bus)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "passion5-hannam",
    name: "Passion 5",
    name_kr: "패션5",
    address: "서울특별시 용산구 이태원로 272",
    city: "seoul",
    area: "Hannam",
    category: "dessert",
    cuisine: null,
    signature: "Luxe bakery & patisserie",
    blurb: "A jewel-box bakery-patisserie near Hannam — glossy cakes and pastries. A dessert lover's playground.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5386494,
    lng: 127.0020823,
    place_id: "ChIJrVB4ELKjfDUREVBLci4IOAw",
    instagram: null,
    hours: null,
    station: "Hangangjin Stn (Line 6)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "working-holiday-gwangan",
    name: "Working Holiday Gwangan",
    name_kr: "워킹홀리데이 광안",
    address: "부산광역시 해운대구 해운대해변로 277 다옴빌딩 5층",
    city: "busan",
    area: "Gwangalli",
    category: "cafe",
    cuisine: null,
    signature: "Beachy Gwangalli cafe",
    blurb: "A bright, breezy Gwangalli cafe (★4.9) with a holiday mood and pretty drinks.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1599125,
    lng: 129.161721,
    place_id: "ChIJgQAEQV6NaDURVU9udPkT78g",
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "momos-coffee-nampo",
    name: "Momos Coffee",
    name_kr: "모모스커피 본점",
    address: "부산광역시 해운대구 마린시티1로 91 101동 1층 101호",
    city: "busan",
    area: "Nampo (Busan)",
    category: "cafe",
    cuisine: null,
    signature: "World-champion specialty coffee",
    blurb: "Home of a World Barista Champion — Busan's most serious specialty coffee in a beautiful flagship.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1544957,
    lng: 129.1443344,
    place_id: "ChIJxVTc7MGTaDUR4786iFUPUTc",
    instagram: null,
    hours: null,
    station: "Nampo area",
    price: "₩₩",
    must_try: false
  },
  {
    id: "coffee-hanyakbang-euljiro",
    name: "Coffee Hanyakbang",
    name_kr: "커피한약방",
    address: "서울특별시 중구 삼일대로12길 16-6",
    city: "seoul",
    area: "Euljiro",
    category: "cafe",
    cuisine: null,
    signature: "Hidden candlelit coffee house",
    blurb: "A hidden Euljiro gem inside an old herbal-medicine building — candlelit, romantic and timeless.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5665301,
    lng: 126.9885936,
    place_id: "ChIJedlDzuWifDURBaOCaa5hkL4",
    instagram: null,
    hours: null,
    station: "Euljiro 3-ga Stn (Lines 2/3)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "standard-bread-haeundae",
    name: "Standard Bread Haeundae",
    name_kr: "스탠다드브레드 해운대",
    address: "부산광역시 해운대구 해운대로 571",
    city: "busan",
    area: "Haeundae",
    category: "dessert",
    cuisine: null,
    signature: "Cult-favorite bakery",
    blurb: "A Haeundae bakery with a devoted following (★4.9) — the pastries sell out fast.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.161337,
    lng: 129.1540882,
    place_id: "ChIJJdhYegCTaDURHJFlgH8Mo-Q",
    instagram: null,
    hours: null,
    station: "Haeundae Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "koriko-cafe-yeonnam",
    name: "Koriko Cafe",
    name_kr: "코리코 카페",
    address: "서울특별시 마포구 성미산로 165-7",
    city: "seoul",
    area: "Yeonnam",
    category: "cafe",
    cuisine: null,
    signature: "Whimsical themed cafe",
    blurb: "A whimsical Yeonnam cafe with pure Kiki's-Delivery-Service energy — a photo favorite.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5650259,
    lng: 126.9247269,
    place_id: "ChIJW2-VzAyZfDURUEzUuNm7Foc",
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "idorim-seoulsup",
    name: "Idorim",
    name_kr: "이도림",
    address: "서울특별시 종로구 자하문로 43 경복궁 본점",
    city: "seoul",
    area: "Seoul Forest",
    category: "matcha",
    cuisine: null,
    signature: "Matcha & traditional teas",
    blurb: "A serene tea cafe by Seoul Forest — matcha and traditional teas in a calm, wooden space.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5799476,
    lng: 126.9710654,
    place_id: "ChIJawHWb_ejfDURUJC1B80y29g",
    instagram: null,
    hours: null,
    station: "Seoul Forest Stn (Suin-Bundang)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "ops-haeundae",
    name: "OPS Haeundae",
    name_kr: "옵스 해운대점",
    address: "부산광역시 해운대구 중동1로 31",
    city: "busan",
    area: "Haeundae",
    category: "dessert",
    cuisine: null,
    signature: "Legendary Busan bakery",
    blurb: "A legendary Busan bakery since the '80s — the pastries are a local rite of passage.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1627911,
    lng: 129.1628989,
    place_id: "ChIJQ8zHkGeNaDURiWBWoDoXAT8",
    instagram: null,
    hours: null,
    station: "Haeundae Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "chungsudang-ikseon",
    name: "Chungsudang",
    name_kr: "청수당 베이커리",
    address: "서울특별시 종로구 돈화문로11나길 31-9",
    city: "seoul",
    area: "Ikseon-dong",
    category: "cafe",
    cuisine: null,
    signature: "Japanese-garden bakery-cafe",
    blurb: "A dreamy garden bakery-cafe in Ikseon-dong — koi pond, greenery and lovely bakes.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5738825,
    lng: 126.9897623,
    place_id: "ChIJFSe90eejfDURnI3qwtRtTF8",
    instagram: null,
    hours: null,
    station: "Jongno 3-ga Stn (Lines 1/3/5)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "chilam-sagye-gijang",
    name: "Chilam Sagye",
    name_kr: "칠암사계",
    address: "부산광역시 기장�� 일광면 칠암1길 7-10",
    city: "busan",
    area: "Gijang",
    category: "cafe",
    cuisine: null,
    signature: "Ocean-view calm",
    blurb: "A serene ocean-view cafe in Gijang — big windows, calm mood, endless sea.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.2999281,
    lng: 129.2594596,
    place_id: "ChIJz3w3lHKHaDURh3RvyAOgtnE",
    instagram: null,
    hours: null,
    station: "Gijang (taxi/bus)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "balbal-vintage-euljiro",
    name: "Balbal Vintage",
    name_kr: "BALBAL VINTAGE",
    address: "서울특별시 중구 명동6길 21",
    city: "seoul",
    area: "Euljiro",
    category: "fashion",
    cuisine: null,
    signature: "Cult vintage clothing",
    blurb: "A cult Euljiro vintage shop (★5) — dig for one-of-a-kind pieces.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5624654,
    lng: 126.9844425,
    place_id: "ChIJ_U25gA6lfDURRrQWPfTv0UY",
    instagram: null,
    hours: null,
    station: "Euljiro 3-ga Stn (Lines 2/3)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "jm-coffee-gijang",
    name: "JM Coffee Roasters",
    name_kr: "제이엠커피로스터스 부산본점",
    address: "부산광역시 기장군 기장읍 대변3길 8",
    city: "busan",
    area: "Gijang",
    category: "cafe",
    cuisine: null,
    signature: "Coastal specialty roaster",
    blurb: "A respected Busan roaster near the coast — clean, careful coffee.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.2228426,
    lng: 129.2316194,
    place_id: "ChIJI0pZ3TiMaDURnx1cAVLQqKg",
    instagram: null,
    hours: null,
    station: "Gijang (taxi/bus)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "terarosa-suyeong",
    name: "Terarosa Suyeong",
    name_kr: "테라로사 수영점",
    address: "부산광역시 수영구 망미제2동 구락로123번길 20",
    city: "busan",
    area: "Suyeong (Gwangalli)",
    category: "cafe",
    cuisine: null,
    signature: "Flagship specialty roaster",
    blurb: "A flagship of Korea's beloved specialty roaster — airy space, excellent coffee near Gwangalli.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1771272,
    lng: 129.1149289,
    place_id: "ChIJsX4KEN-SaDURzjPnpAm-iR0",
    instagram: null,
    hours: null,
    station: "Gwangan Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "maxim-plant-hannam",
    name: "Maxim Plant",
    name_kr: "맥심플랜트",
    address: "서울특별시 용산구 이태원로 250",
    city: "seoul",
    area: "Hannam",
    category: "cafe",
    cuisine: null,
    signature: "Plant-filled flagship cafe",
    blurb: "A greenhouse-like flagship cafe in Hannam — plants everywhere and good coffee.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5369732,
    lng: 127.0009643,
    place_id: "ChIJ-9VNi1GjfDURDUg_MSuPYc8",
    instagram: null,
    hours: null,
    station: "Hangangjin Stn (Line 6)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "knotted-studio-cheongdam",
    name: "Knotted Studio Cheongdam",
    name_kr: "노티드 스튜디오 청담",
    address: "서울특별시 강남구 도산대로53길 15",
    city: "seoul",
    area: "Cheongdam (Apgujeong)",
    category: "dessert",
    cuisine: null,
    signature: "Flagship of the cult donut brand",
    blurb: "The flagship of Korea's cult donut brand — pastel, playful and very Instagrammable.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5241508,
    lng: 127.0382334,
    place_id: "ChIJc16A6IijfDURZq2YlJKJEOI",
    instagram: null,
    hours: null,
    station: "Apgujeong Rodeo Stn",
    price: "₩₩",
    must_try: false
  },
  {
    id: "soha-salt-pond-ikseon",
    name: "Soha Salt Pond",
    name_kr: "소하염전",
    address: "서울특별시 종로구 수표로28길 21-5",
    city: "seoul",
    area: "Ikseon-dong",
    category: "cafe",
    cuisine: null,
    signature: "Hanok cafe with a water garden",
    blurb: "A tranquil hanok cafe in Ikseon-dong with a little water garden — pure calm.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5730739,
    lng: 126.9896949,
    place_id: "ChIJdawuLnGjfDURFoQHgAgusNI",
    instagram: null,
    hours: null,
    station: "Jongno 3-ga Stn (Lines 1/3/5)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "cafe-yoon-songjeong",
    name: "Cafe Yoon",
    name_kr: "카페 윤",
    address: "부산광역시 기장군 기장해안로 34-16",
    city: "busan",
    area: "Songjeong (Busan)",
    category: "cafe",
    cuisine: null,
    signature: "Pretty beach-town cafe",
    blurb: "A pretty Songjeong cafe near the beach — relaxed and photogenic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1819187,
    lng: 129.2112746,
    place_id: "ChIJQxoYtDiMaDURdLdtW1L3y4M",
    instagram: null,
    hours: null,
    station: "Songjeong area",
    price: "₩₩",
    must_try: false
  },
  {
    id: "osulloc-bukchon",
    name: "Osulloc Tea House (Bukchon)",
    name_kr: "오설록 티하우스 북촌점",
    address: "서울특별시 종로구 북촌로 45",
    city: "seoul",
    area: "Bukchon (Samcheong)",
    category: "matcha",
    cuisine: null,
    signature: "Jeju green tea, matcha desserts & ice cream",
    blurb: "Korea's famous Jeju green-tea house — matcha and green-tea desserts in a lovely Bukchon setting.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5810441,
    lng: 126.984653,
    place_id: "ChIJx3KYRuSjfDURTmn2MdETH0k",
    instagram: null,
    hours: null,
    station: "Anguk Stn (Line 3)",
    price: "₩₩",
    must_try: true
  },
  {
    id: "coralani-songjeong",
    name: "Coralani",
    name_kr: "코랄라니",
    address: "부산광역시 기장군 기장해안로 32",
    city: "busan",
    area: "Songjeong (Busan)",
    category: "cafe",
    cuisine: null,
    signature: "Beach-holiday mood cafe",
    blurb: "A breezy Songjeong cafe with a beach-holiday feel.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1824072,
    lng: 129.2088791,
    place_id: "ChIJbanmhfSNaDURtt1N0sfVwwQ",
    instagram: null,
    hours: null,
    station: "Songjeong area",
    price: "₩₩",
    must_try: false
  },
  {
    id: "bibibidang-haeundae",
    name: "Bibibidang",
    name_kr: "비비비당",
    address: "부산광역시 해운대구 달맞이길 239-16",
    city: "busan",
    area: "Dalmaji-gil (Haeundae)",
    category: "cafe",
    cuisine: null,
    signature: "Traditional tea house with sea views",
    blurb: "A traditional tea house on Dalmaji hill with sweeping sea views — teas, patbingsu and Korean sweets.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1624833,
    lng: 129.1850753,
    place_id: "ChIJB96GBBCNaDUR7MTdJQJQFU0",
    instagram: null,
    hours: null,
    station: "Jung-dong (Haeundae, Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "london-bagel-dosan",
    name: "London Bagel Museum (Dosan)",
    name_kr: "런던베이글뮤지엄 도산점",
    address: "서울특별시 강남구 언주로168길 33",
    city: "seoul",
    area: "Dosan (Apgujeong)",
    category: "dessert",
    cuisine: null,
    signature: "Korea's famous bagels",
    blurb: "Korea's bagel craze in one photogenic shop — expect a line; the cream-cheese bagels are the move.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5260427,
    lng: 127.0364261,
    place_id: "ChIJGTEOTEqjfDUR3PisqqSTRkE",
    instagram: null,
    hours: null,
    station: "Apgujeong Rodeo Stn",
    price: "₩₩",
    must_try: true
  },
  {
    id: "waggle-waggle-euljiro",
    name: "Waggle Waggle Bake Shop",
    name_kr: "와글와글베이크샵",
    address: "서울특별시 중구 을지로 245",
    city: "seoul",
    area: "Euljiro",
    category: "dessert",
    cuisine: null,
    signature: "Cult cakes & cookies",
    blurb: "A charming Euljiro bake shop (★4.8) with cult-favorite cakes and cookies.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5677664,
    lng: 127.0071134,
    place_id: "ChIJA7n2vKqjfDURWOuoV6Qlca0",
    instagram: null,
    hours: null,
    station: "Euljiro 3-ga Stn (Lines 2/3)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "kokorokara-yeonnam",
    name: "Kokorokara",
    name_kr: "코코로카라",
    address: "서울특별시 마포구 연남동 1길 41",
    city: "seoul",
    area: "Yeonnam",
    category: "dessert",
    cuisine: null,
    signature: "Delicate handmade sweets",
    blurb: "A tiny Yeonnam dessert shop (★4.9) beloved for its delicate, handmade sweets.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5598136,
    lng: 126.9209279,
    place_id: "ChIJzcwmbrCZfDURjhNsBV85z6c",
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "leah-cafe-samcheong",
    name: "Leah Cafe",
    name_kr: "레아 카페",
    address: "서울특별시 종로구 인사동길 51 2층",
    city: "seoul",
    area: "Samcheong",
    category: "dessert",
    cuisine: null,
    signature: "Calm cafe near the palaces",
    blurb: "A calm, pretty Samcheong cafe (★5) for coffee and cake between the palaces.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5745856,
    lng: 126.9839478,
    place_id: "ChIJQ8dui8KifDURVVd13i-MmS4",
    instagram: null,
    hours: null,
    station: "Anguk Stn (Line 3)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "chiffle-yeonnam",
    name: "Chiffle",
    name_kr: "치플레",
    address: "서울특별시 마포구 동교로 262-9 1층",
    city: "seoul",
    area: "Yeonnam",
    category: "dessert",
    cuisine: null,
    signature: "Airy chiffon-style treats",
    blurb: "A Yeonnam dessert spot (★4.9) famous for its light, airy treats.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5628284,
    lng: 126.9256462,
    place_id: "ChIJi2c6EMSZfDUROuEilOmRekQ",
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "eternal-journey-ananti",
    name: "Eternal Journey (Ananti Cove)",
    name_kr: "아난티 코브 이터널저니",
    address: "부산광역시 기장군 기장읍 기장해안로 268-31",
    city: "busan",
    area: "Gijang (Ananti Cove)",
    category: "shop",
    cuisine: null,
    signature: "Stunning design bookstore",
    blurb: "A breathtaking design bookstore at Ananti Cove — soaring shelves; a destination in itself.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1976859,
    lng: 129.2283542,
    place_id: "ChIJUVWGSK-OaDURxdnMpYdNLGo",
    instagram: null,
    hours: null,
    station: "Gijang (taxi/bus)",
    price: "₩₩",
    must_try: false
  },

  {
    id: "gwangjang-market",
    name: "Gwangjang Market",
    name_kr: "광장시장",
    address: "서울특별시 종로구 청계천로 88",
    city: "seoul",
    area: "Jongno",
    category: "landmark",
    cuisine: null,
    signature: "시장",
    blurb: "Seoul's iconic old market — a maze of food stalls (bindaetteok, mayak gimbap) and vintage. Loud, lively, unforgettable.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5700398,
    lng: 126.9996036,
    place_id: "ChIJm3V0fu2ifDURRJ8IMUijVtY",
    instagram: null,
    hours: null,
    station: "Jongno 5-ga Stn (Line 1)",
    price: "Free",
    must_try: true
  },
  {
    id: "namdaemun-market",
    name: "Namdaemun Market",
    name_kr: "남대문시장",
    address: "서울특별시 중구 남대문시장4길 21",
    city: "seoul",
    area: "Jung-gu",
    category: "landmark",
    cuisine: null,
    signature: "시장",
    blurb: "Korea's largest traditional market — endless alleys of goods, street food and bargains near the old gate.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.559277,
    lng: 126.9777029,
    place_id: "ChIJfYjlFvWifDURYSDsoxYbN80",
    instagram: null,
    hours: null,
    station: "Hoehyeon Stn (Line 4)",
    price: "Free",
    must_try: false
  },
  {
    id: "deoksugung",
    name: "Deoksugung Palace",
    name_kr: "덕수궁",
    address: "서울특별시 중구 세종대로 99 덕수궁",
    city: "seoul",
    area: "Jung-gu",
    category: "landmark",
    cuisine: null,
    signature: "문화적 랜드마크",
    blurb: "A palace where hanok meets Western architecture, right downtown — lovely stone-wall walk and evening light.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5658862,
    lng: 126.9749017,
    place_id: "ChIJMcWZMY2ifDUR2NLv8F3Togc",
    instagram: null,
    hours: null,
    station: "City Hall Stn (Lines 1/2)",
    price: "Free",
    must_try: true
  },
  {
    id: "changdeokgung",
    name: "Changdeokgung Palace",
    name_kr: "창덕궁",
    address: "서울특별시 종로구 율곡로 99",
    city: "seoul",
    area: "Jongno",
    category: "landmark",
    cuisine: null,
    signature: "문화적 랜드마크",
    blurb: "A UNESCO palace with the exquisite Secret Garden — arguably Seoul's most beautiful. Book the garden tour.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5794309,
    lng: 126.9910426,
    place_id: "ChIJ4wh0zluifDURaFBW2pdrKf8",
    instagram: null,
    hours: null,
    station: "Anguk Stn (Line 3)",
    price: "Free",
    must_try: true
  },
  {
    id: "changgyeonggung",
    name: "Changgyeonggung Palace",
    name_kr: "창경궁",
    address: "서울특별시 종로구 창경궁로 185",
    city: "seoul",
    area: "Jongno",
    category: "landmark",
    cuisine: null,
    signature: "",
    blurb: "A quieter royal palace with ponds and a greenhouse — peaceful, especially at dusk.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5788149,
    lng: 126.9949298,
    place_id: "ChIJN9jfPNaifDURz_NR6E1r4Eo",
    instagram: null,
    hours: null,
    station: "Hyehwa Stn (Line 4)",
    price: "Free",
    must_try: false
  },
  {
    id: "seoul-sky",
    name: "Seoul Sky (Lotte Tower)",
    name_kr: "서울스카이",
    address: "서울특별시 송파구 올림픽로 300",
    city: "seoul",
    area: "Jamsil (Songpa)",
    category: "landmark",
    cuisine: null,
    signature: "전망대",
    blurb: "The glass-floored observatory atop Korea's tallest tower — dizzying, dazzling city views. Best at sunset.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5125295,
    lng: 127.102305,
    place_id: "ChIJu7dpc45FezURhLMS5U5eaJk",
    instagram: null,
    hours: null,
    station: "Jamsil Stn (Lines 2/8)",
    price: "Free",
    must_try: true
  },
  {
    id: "mmca-seoul",
    name: "MMCA Seoul",
    name_kr: "국립현대미술관 서울",
    address: "서울특별시 종로구 삼청로 30",
    city: "seoul",
    area: "Samcheong (Jongno)",
    category: "landmark",
    cuisine: null,
    signature: "Art museum",
    blurb: "The national museum of modern art, tucked by the palaces — great exhibitions and a calm courtyard.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5788333,
    lng: 126.9804281,
    place_id: "ChIJRynTqcaifDURBaSFx8HncPs",
    instagram: null,
    hours: null,
    station: "Anguk Stn (Line 3)",
    price: "Free",
    must_try: false
  },
  {
    id: "banpo-hangang-park",
    name: "Banpo Hangang Park",
    name_kr: "반포한강공원",
    address: "서울특별시 서초구 신반포로11길 40",
    city: "seoul",
    area: "Seocho",
    category: "landmark",
    cuisine: null,
    signature: "공원",
    blurb: "Home of the Banpo Bridge Rainbow Fountain — picnic by the river and catch the evening water show.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5103503,
    lng: 126.9952372,
    place_id: "ChIJOY4n3RVFezURFvaFVfFmrO0",
    instagram: null,
    hours: null,
    station: "Express Bus Terminal Stn",
    price: "Free",
    must_try: false
  },
  {
    id: "mangwon-market",
    name: "Mangwon Market",
    name_kr: "망원시장",
    address: "서울특별시 마포구 포은로6길 27",
    city: "seoul",
    area: "Mangwon (Mapo)",
    category: "landmark",
    cuisine: null,
    signature: "시장",
    blurb: "A friendly local market loved for cheap, delicious street food — pair it with a Mangwon cafe stroll.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5559018,
    lng: 126.9062854,
    place_id: "ChIJA6gxryiZfDURJvmbeBvdz_Y",
    instagram: null,
    hours: null,
    station: "Mangwon Stn (Line 6)",
    price: "Free",
    must_try: false
  },
  {
    id: "songdo-cable-car",
    name: "Songdo Cable Car",
    name_kr: "송도 베이스테이션(해상케이블카)",
    address: "부산광역시 서구 송도해변로 171",
    city: "busan",
    area: "Songdo (Seo-gu)",
    category: "landmark",
    cuisine: null,
    signature: "관광 명소",
    blurb: "A glass-floor cable car gliding over Songdo's sea — thrilling views and a pretty beach below.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.0763876,
    lng: 129.0236199,
    place_id: "ChIJQehEaUToaDURU7CTL4IJmZY",
    instagram: null,
    hours: null,
    station: "Songdo (taxi/bus)",
    price: "Free",
    must_try: true
  },
  {
    id: "oryukdo-skywalk",
    name: "Oryukdo Skywalk",
    name_kr: "오륙도 스카이워크",
    address: "부산광역시 남구 오륙도로 137",
    city: "busan",
    area: "Nam-gu",
    category: "landmark",
    cuisine: null,
    signature: "전망대",
    blurb: "A glass walkway jutting over the cliffs where the sea meets the rocky islets — bracing and beautiful.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1006767,
    lng: 129.1244009,
    place_id: "ChIJVRLdCsjtaDURcdummQTLnRk",
    instagram: null,
    hours: null,
    station: "Oryukdo (bus)",
    price: "Free",
    must_try: false
  },
  {
    id: "busan-tower",
    name: "Busan Tower",
    name_kr: "부산타워",
    address: "부산광역시 중구 용두산길 37-55",
    city: "busan",
    area: "Nampo (Yongdusan)",
    category: "landmark",
    cuisine: null,
    signature: "전망대",
    blurb: "The city's classic tower in Yongdusan Park — panoramic harbor views over Nampo.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1011913,
    lng: 129.0323697,
    place_id: "ChIJq0OD23TpaDURTv9SBp0VWtI",
    instagram: null,
    hours: null,
    station: "Nampo Stn (Line 1)",
    price: "Free",
    must_try: false
  },
  {
    id: "busan-citizens-park",
    name: "Busan Citizens Park",
    name_kr: "부산시민공원",
    address: "부산광역시 부산진구 시민공원로 73",
    city: "busan",
    area: "Busanjin",
    category: "landmark",
    cuisine: null,
    signature: "시티 공원",
    blurb: "A big, beautifully landscaped park — fountains, lawns and shade near Seomyeon.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1681608,
    lng: 129.0573853,
    place_id: "ChIJPbq4_UHraDURSKskEXfxKno",
    instagram: null,
    hours: null,
    station: "Bujeon Stn",
    price: "Free",
    must_try: false
  },
  {
    id: "yongdusan-park",
    name: "Yongdusan Park",
    name_kr: "용두산공원",
    address: "부산광역시 중구 용두산길 37-55",
    city: "busan",
    area: "Nampo (Jung-gu)",
    category: "landmark",
    cuisine: null,
    signature: "공원",
    blurb: "A hilltop park above Nampo with Busan Tower, pigeons and sea views — easy escalator up.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1006536,
    lng: 129.0326226,
    place_id: "ChIJl8gXNgvpaDURP6m_S0gwF74",
    instagram: null,
    hours: null,
    station: "Nampo Stn (Line 1)",
    price: "Free",
    must_try: false
  },
  {
    id: "cheongsapo-observatory",
    name: "Cheongsapo Daritdol Observatory",
    name_kr: "청사포 다릿돌전망대",
    address: "부산광역시 해운대구 중동 산3-9",
    city: "busan",
    area: "Cheongsapo (Haeundae)",
    category: "landmark",
    cuisine: null,
    signature: "전망대",
    blurb: "A skywalk observatory over Cheongsapo's blue water — pair it with the Sky Capsule ride.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1640365,
    lng: 129.1967173,
    place_id: "ChIJUQsDVhuNaDURJo5GeByloeQ",
    instagram: null,
    hours: null,
    station: "Cheongsapo (Blueline Park)",
    price: "Free",
    must_try: false
  },
  {
    id: "beomeosa",
    name: "Beomeosa Temple",
    name_kr: "범어사",
    address: "부산광역시 금정구 범어사로 250",
    city: "busan",
    area: "Geumjeong",
    category: "landmark",
    cuisine: null,
    signature: "불교사찰",
    blurb: "A serene 1,300-year-old mountain temple — incense, old timber and forest quiet above the city.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.2839899,
    lng: 129.0687639,
    place_id: "ChIJsQ63-9KWaDURQmHr0J6VF_4",
    instagram: null,
    hours: null,
    station: "Beomeosa Stn (Line 1) + bus",
    price: "Free",
    must_try: false
  },
  {
    id: "songdo-beach",
    name: "Songdo Beach",
    name_kr: "송도해수욕장",
    address: "부산광역시 서구 암남동 135-5",
    city: "busan",
    area: "Seo-gu",
    category: "landmark",
    cuisine: null,
    signature: "관광 명소",
    blurb: "Busan's oldest beach — a gentle cove with a sky walk, cable car and a cloud-trolley.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.0754062,
    lng: 129.0167859,
    place_id: "ChIJyRSSE0XoaDURE2ZwUvqYXKo",
    instagram: null,
    hours: null,
    station: "Songdo (taxi/bus)",
    price: "Free",
    must_try: false
  },
  {
    id: "donggung-wolji",
    name: "Donggung Palace & Wolji Pond",
    name_kr: "동궁과 월지",
    address: "경상북도 경주시 원화로 102",
    city: "gyeongju",
    area: "Gyeongju",
    category: "landmark",
    cuisine: null,
    signature: "역사적 명소",
    blurb: "A former royal pleasure palace mirrored in a pond — breathtaking after dark when it's lit up.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.8348173,
    lng: 129.2265645,
    place_id: "ChIJ9SUiOHBOZjUR_YnH8Lbjzt0",
    instagram: null,
    hours: null,
    station: "Gyeongju (daytrip)",
    price: "Free",
    must_try: true
  },
  {
    id: "woljeonggyo",
    name: "Woljeonggyo Bridge",
    name_kr: "경주 월정교",
    address: "경상북도 경주시 교동 48",
    city: "gyeongju",
    area: "Gyeongju",
    category: "landmark",
    cuisine: null,
    signature: "관광 명소",
    blurb: "A reconstructed wooden Silla-era bridge, glowing over the river at night. A photo dream.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.8291928,
    lng: 129.2181213,
    place_id: "ChIJI6-IFWBOZjURG2fe65bJAs0",
    instagram: null,
    hours: null,
    station: "Gyeongju (daytrip)",
    price: "Free",
    must_try: false
  },
  {
    id: "gyeongju-museum",
    name: "Gyeongju National Museum",
    name_kr: "국립경주박물관",
    address: "경상북도 경주시 일정로 186 국립경주박물관",
    city: "gyeongju",
    area: "Gyeongju",
    category: "landmark",
    cuisine: null,
    signature: "박물관",
    blurb: "The best window into the ancient Silla kingdom — golden crowns, bells and treasures.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.8294464,
    lng: 129.2278919,
    place_id: "ChIJRawRj0NOZjURV-Bwn4zSng4",
    instagram: null,
    hours: null,
    station: "Gyeongju (daytrip)",
    price: "Free",
    must_try: false
  },
  {
    id: "seokguram",
    name: "Seokguram Grotto",
    name_kr: "대한불교조계종 석굴암",
    address: "경상북도 경주시 석굴로 238",
    city: "gyeongju",
    area: "Gyeongju",
    category: "landmark",
    cuisine: null,
    signature: "불교사찰",
    blurb: "A UNESCO stone Buddha in a mountain grotto — a hushed, moving masterpiece of Silla art.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.7951981,
    lng: 129.3503599,
    place_id: "ChIJCQ6QQNqyZzUR0ujHdOUux88",
    instagram: null,
    hours: null,
    station: "Gyeongju (daytrip)",
    price: "Free",
    must_try: false
  },
  {
    id: "hwangnidan-gil",
    name: "Hwangnidan-gil",
    name_kr: "황리단길",
    address: "경상북도 경주시 황남동 포석로 일대",
    city: "gyeongju",
    area: "Gyeongju",
    category: "photo",
    cuisine: null,
    signature: "관광 명소",
    blurb: "Gyeongju's trendy old-town street — hanok cafes, boutiques and photo spots by the royal tombs.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.8376609,
    lng: 129.209724,
    place_id: "ChIJA8nY8ExPZjURPC-8kcf4l4E",
    instagram: null,
    hours: null,
    station: "Gyeongju (daytrip)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "muut-seongsu",
    name: "MUUT Seongsu",
    name_kr: "뭍 성수 플래그쉽 스토어(MUUT SEONGSU FLAGSHIP STORE)",
    address: "서울특별시 성동구 연무장길 94 2층",
    city: "seoul",
    area: "Seongsu",
    category: "shop",
    cuisine: null,
    signature: "상점",
    blurb: "A minimalist Seongsu flagship of design objects and homeware — beautifully curated.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5410508,
    lng: 127.0595319,
    place_id: "ChIJV4hbLXylfDURy6Cz_dzN5Ow",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "oimu-bukchon",
    name: "OIMU (Bukchon)",
    name_kr: "OIMU Bukchon store (오이뮤 북촌)",
    address: "서울특별시 종로구 윤보선길 65",
    city: "seoul",
    area: "Bukchon (Jongno)",
    category: "shop",
    cuisine: null,
    signature: "선물 가게",
    blurb: "A design brand reviving Korean heritage in stationery and objects — a lovely Bukchon gift stop.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5788612,
    lng: 126.983078,
    place_id: "ChIJdzqxE6qjfDURu9-W5hCyP4U",
    instagram: null,
    hours: null,
    station: "Anguk Stn (Line 3)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "lcdc-seoul",
    name: "LCDC Seoul",
    name_kr: "LCDC Seoul",
    address: "서울특별시 성동구 성수동2가 연무장17길 10",
    city: "seoul",
    area: "Seongsu",
    category: "shop",
    cuisine: null,
    signature: "상점",
    blurb: "A stylish Seongsu concept complex of design shops and a cafe — browse the whole building.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5415795,
    lng: 127.0614594,
    place_id: "ChIJM_O6RYqlfDURu7rlx8Fvdtg",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "alpha-namdaemun",
    name: "Alpha Stationery (Namdaemun)",
    name_kr: "알파 남대문본점",
    address: "서울특별시 중구 남대문로 6-2",
    city: "seoul",
    area: "Namdaemun (Jung-gu)",
    category: "shop",
    cuisine: null,
    signature: "상점",
    blurb: "A giant stationery-and-art-supplies emporium — floors of pens, paper and crafts.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5601221,
    lng: 126.9765898,
    place_id: "ChIJG5HR2PSifDURYEw2aB5Uqso",
    instagram: null,
    hours: null,
    station: "Hoehyeon Stn (Line 4)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "route-hongdae",
    name: "Route Hongdae",
    name_kr: "루트홍대",
    address: "서울특별시 마포구 양화로 140 지하 1층",
    city: "seoul",
    area: "Hongdae",
    category: "fashion",
    cuisine: null,
    signature: "의류점",
    blurb: "A massive, beloved Hongdae vintage store (★5) — hours of racks to dig through.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5549048,
    lng: 126.9221223,
    place_id: "ChIJJwM3CsmZfDURkbyJbTCuPu0",
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "fox-vintage-seoulsup",
    name: "Fox Vintage (Seoul Forest)",
    name_kr: "fox vintage, 서울숲",
    address: "서울특별시 성동구 성수동1가 번지 지1층 668-100",
    city: "seoul",
    area: "Seoul Forest / Seongsu",
    category: "fashion",
    cuisine: null,
    signature: "의류점",
    blurb: "A well-curated vintage shop near Seoul Forest — quality pieces, not just quantity.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5475496,
    lng: 127.0427266,
    place_id: "ChIJ_yV1gJ6kfDUR7PTqgteAzVI",
    instagram: null,
    hours: null,
    station: "Seoul Forest Stn (Suin-Bundang)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "air-vintage",
    name: "AIR Vintage",
    name_kr: "AIR vintage",
    address: "서울특별시 성동구 연무장길 39 B1",
    city: "seoul",
    area: "Seongsu",
    category: "fashion",
    cuisine: null,
    signature: "의류점",
    blurb: "A crisp, well-edited vintage store loved for its selection and displays.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5430482,
    lng: 127.0537658,
    place_id: "ChIJBY-UDwClfDURJkbbas8FTJs",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "4f-vintage",
    name: "4F Vintage",
    name_kr: "4Fvintage (사층빈티지)",
    address: "서울특별시 마포구 양화로 177",
    city: "seoul",
    area: "Hongdae",
    category: "fashion",
    cuisine: null,
    signature: "의류점",
    blurb: "A vintage favorite for one-of-a-kind finds — a proper thrifting rabbit hole.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5578401,
    lng: 126.9247215,
    place_id: "ChIJkdk-tyuZfDURQpD9R0ITKhQ",
    instagram: null,
    hours: null,
    station: "Hongik Univ. Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "luvluvluv-seongsu",
    name: "LuvLuvLuv Seongsu",
    name_kr: "러브러브러브 성수(LuvLuvLuv)",
    address: "서울특별시 성동구 연무장길 38",
    city: "seoul",
    area: "Seongsu",
    category: "fashion",
    cuisine: null,
    signature: "의류점",
    blurb: "A playful Seongsu fashion flagship (★5) — trend-forward and very photogenic.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5428458,
    lng: 127.0534563,
    place_id: "ChIJX2XakkmlfDURGTfd3Rd6z_M",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "low-classic-seongsu",
    name: "Low Classic Seongsu",
    name_kr: "LOW CLASSIC Seongsu",
    address: "서울특별시 성동구 연무장길 86",
    city: "seoul",
    area: "Seongsu",
    category: "fashion",
    cuisine: null,
    signature: "의류점",
    blurb: "The flagship of a respected Korean women's label — minimalist, elevated basics.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5413088,
    lng: 127.0586831,
    place_id: "ChIJe0N7VQClfDURlmt4x-x5-M0",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "kasina-seongsu",
    name: "Kasina Seongsu",
    name_kr: "카시나 성수 Kasina Seongsu",
    address: "서울특별시 성동구 성수이로7길 41",
    city: "seoul",
    area: "Seongsu",
    category: "fashion",
    cuisine: null,
    signature: "신발 판매점",
    blurb: "A cult Korean sneaker-and-streetwear flagship — great for kicks and collabs.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5425947,
    lng: 127.0531067,
    place_id: "ChIJrbauhZylfDUR7dMXcUuOg74",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "forest-vintage",
    name: "Forest Vintage",
    name_kr: "FOREST VINTAGE",
    address: "서울특별시 성동구 성수동1가 668-61 B1F",
    city: "seoul",
    area: "Seongsu",
    category: "fashion",
    cuisine: null,
    signature: "의류점",
    blurb: "A curated vintage shop (★5) with a warm, woodsy feel — treasure-hunt in comfort.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5465218,
    lng: 127.0430513,
    place_id: "ChIJk7RYusmlfDURO1S6PrVr0H0",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "vintage-santa-seongsu",
    name: "Vintage Santa Seongsu",
    name_kr: "빈티지산타 성수(VINTAGE SANTA SEONGSU)",
    address: "서울특별시 성동구 성수이로 89 지하 1층",
    city: "seoul",
    area: "Seongsu",
    category: "fashion",
    cuisine: null,
    signature: "의류점",
    blurb: "A packed, fun vintage store in Seongsu — dig for retro gems.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5429195,
    lng: 127.0563087,
    place_id: "ChIJV5A3N4ilfDURf-_6F5k2uwM",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "rawrow-seongsu",
    name: "Rawrow Seongsu",
    name_kr: "로우로우 월드와이드서울 성수점 (RAWROW WORLDWIDESEOUL SEONGSU)",
    address: "서울특별시 성동구 성수이로7길 24 1층",
    city: "seoul",
    area: "Seongsu",
    category: "fashion",
    cuisine: null,
    signature: "상점",
    blurb: "A sleek Korean bag-and-accessories brand flagship — understated, well-made everyday pieces.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 37.5413837,
    lng: 127.0543236,
    place_id: "ChIJ6-UHdMSYfDURv7QsN48R_jA",
    instagram: null,
    hours: null,
    station: "Seongsu Stn (Line 2)",
    price: "₩₩",
    must_try: false
  },
  {
    id: "luft-mansion-busan",
    name: "Luft Mansion",
    name_kr: "루프트맨션(Luft Mansion)",
    address: "부산광역시 해운대구 우동1로38번가길 1 2층 201호",
    city: "busan",
    area: "Busan",
    category: "fashion",
    cuisine: null,
    signature: "상점",
    blurb: "A stylish Busan select shop (★5) — fashion and objects in a beautifully done space.",
    spice: 0,
    pork_lamb_free: null,
    photo_spot: true,
    lat: 35.1650936,
    lng: 129.1580595,
    place_id: "ChIJzbVGQzGNaDUR0dPT3aoFe3o",
    instagram: null,
    hours: null,
    station: "Busan (see map)",
    price: "₩₩",
    must_try: false
  }

  // ---------- TODO (next passes) ----------
  // COORDS: newly-added spots have lat/lng/place_id = null (Google resolves them by name for now).
  //         Add exact coords when convenient — needed only for the optional My Maps overview.
  // MORE:   Seoul chinese ×1 more (pork-free), a Busan korean seafood restaurant, more desserts.
  // JAPAN:  add as 3rd tab later (Tokyo? Osaka? Kyoto? Uji = matcha holy land) — ask Linda her cities.
];
