// Situational phrases — Korean + Japanese + English. Tap one to show it big to staff.
const PHRASES = [
  { cat: "Basics", emoji: "👋", items: [
    { en: "Hello", ko: "안녕하세요", ja: "こんにちは" },
    { en: "Thank you", ko: "감사합니다", ja: "ありがとうございます" },
    { en: "Excuse me", ko: "저기요", ja: "すみません" },
    { en: "Sorry", ko: "죄송합니다", ja: "ごめんなさい" },
    { en: "Yes / No", ko: "네 / 아니요", ja: "はい / いいえ" },
    { en: "Do you speak English?", ko: "영어 하세요?", ja: "英語を話せますか?" },
    { en: "How much is it?", ko: "얼마예요?", ja: "いくらですか?" },
    { en: "A little, please", ko: "조금만요", ja: "少しだけお願いします" },
  ]},
  { cat: "No pork/lamb", emoji: "🚫🥓", items: [
    { en: "No pork, please", ko: "돼지고기 빼주세요", ja: "豚肉を抜いてください" },
    { en: "No pork OR lamb, please", ko: "돼지고기랑 양고기 빼주세요", ja: "豚肉と羊肉は抜いてください" },
    { en: "Does this have pork?", ko: "이거 돼지고기 들어가요?", ja: "これに豚肉は入っていますか?" },
    { en: "Does this have lamb?", ko: "이거 양고기 들어가요?", ja: "これに羊肉は入っていますか?" },
    { en: "I can't eat pork or lamb", ko: "돼지고기랑 양고기는 못 먹어요", ja: "豚肉と羊肉は食べられません" },
    { en: "Not too spicy, please", ko: "너무 맵지 않게 해주세요", ja: "あまり辛くしないでください" },
    { en: "I have a food allergy", ko: "저 음식 알레르기가 있어요", ja: "食物アレルギーがあります" },
  ]},
  { cat: "Ordering", emoji: "🍽️", items: [
    { en: "Table for one / two", ko: "한 명이요 / 두 명이요", ja: "一人です / 二人です" },
    { en: "This one, please", ko: "이거 주세요", ja: "これをください" },
    { en: "What do you recommend?", ko: "추천 메뉴 있어요?", ja: "おすすめは何ですか?" },
    { en: "Water, please", ko: "물 주세요", ja: "お水ください" },
    { en: "Is this vegetarian?", ko: "이거 채식이에요?", ja: "これはベジタリアンですか?" },
    { en: "The bill, please", ko: "계산해 주세요", ja: "お会計お願いします" },
    { en: "To go, please", ko: "포장해 주세요", ja: "持ち帰りでお願いします" },
    { en: "It was delicious!", ko: "정말 맛있었어요!", ja: "とても美味しかったです!" },
  ]},
  { cat: "Getting around", emoji: "🚕", items: [
    { en: "Please take me here (show map) →", ko: "여기로 가주세요", ja: "ここまでお願いします" },
    { en: "Where is the subway station?", ko: "지하철역이 어디예요?", ja: "駅はどこですか?" },
    { en: "Where is the bathroom?", ko: "화장실이 어디예요?", ja: "トイレはどこですか?" },
    { en: "Please stop here", ko: "여기서 세워주세요", ja: "ここで止めてください" },
    { en: "How do I get to…?", ko: "…까지 어떻게 가요?", ja: "…までどう行きますか?" },
    { en: "Is it far?", ko: "여기서 멀어요?", ja: "ここから遠いですか?" },
  ]},
  { cat: "Shopping", emoji: "🛍️", items: [
    { en: "Can I try it on?", ko: "입어봐도 돼요?", ja: "試着してもいいですか?" },
    { en: "Do you have another size?", ko: "다른 사이즈 있어요?", ja: "他のサイズはありますか?" },
    { en: "Can I pay by card?", ko: "카드 돼요?", ja: "カードは使えますか?" },
    { en: "Tax refund, please", ko: "택스 리펀 돼요?", ja: "免税できますか?" },
    { en: "Just looking, thank you", ko: "그냥 구경할게요", ja: "見ているだけです" },
    { en: "Can I get a bag?", ko: "봉투 주세요", ja: "袋をください" },
  ]},
  { cat: "Help", emoji: "🆘", items: [
    { en: "Can you help me?", ko: "도와주실 수 있어요?", ja: "助けてもらえますか?" },
    { en: "I'm lost", ko: "길을 잃었어요", ja: "道に迷いました" },
    { en: "Please call the police", ko: "경찰 좀 불러주세요", ja: "警察を呼んでください" },
    { en: "I need a hospital", ko: "병원에 가야 해요", ja: "病院に行きたいです" },
    { en: "Where can I find a pharmacy?", ko: "약국이 어디예요?", ja: "薬局はどこですか?" },
  ]},
];
